### ISSUE TITLE
Tab Groups

### ISSUE THREAD

**Issue by antfu** [nuxt/devtools#111]
We have quite a few tabs right now, and we plan to have many more, in addition to more and more modules contributing to it. The navbar will grow quite long as we go. We should provide a way to better organize them and make groups expandable.

**Comment by Atinux** [comment]
What structure would you suggest @antfu ?

**Comment by Atinux** [comment]
In that case, we need to list all the categories or should they be dynamic as well? 🤔

**Comment by antfu** [comment]
At first, I think we could hard-coded a TS enum for that

**Comment by ManUtopiK** [comment]
A fuse search input at the top of the list could be useful too...

**Comment by antfu** [comment]
Supported the basic: https://github.com/nuxt/devtools/commit/64c48cdf55a756d5263cf8ebfa308258b68a47b5

Later I am thinking we could ask users to peek their usage. Saying "I am a Nuxt user", "I am a module author" to provide different presets on enabled tabs.

**Comment by antfu** [comment]
After a second thought, currently, we don't have many tabs to distinguish between a user and a module author, adding this preset system for toggling only three tabs sounds a bit overkill. Closing this for now and we might revise this idea later.
