### ISSUE TITLE
Reuse Nuxt's WebSocket

### ISSUE THREAD

**Issue by antfu** [nuxt/devtools#112]
Currently, we are creating a new WS entry to do server-client communication:

https://github.com/nuxt/devtools/blob/703b69afb6d5d135f96d1c1c1432351edcaab0cf/packages/devtools/src/module-main.ts#L58-L59

Since Nuxt DevTools is relying on Vite (I see in the near future, we probably only support Vite), I guess reusing Vite's WS would make things more efficient and stable. As Vite has the capability of handling custom events now: https://github.com/vitejs/vite/pull/7437

This could potentially solve the connection issue in back-proxy or dockers, as Vite handles them well. Also could align with the approaches of vite-plugin-inspect etc.

/cc @pi0 you mentioned previously about reusing WS from Nitro, do you think it's still a thing, and what's your opinion on choosing which over which?

**Comment by pi0** [comment]
I believe the second port (either the vite or custom port we are currently using for devtools) would share the same issues for remote sharing and docker as it needs extra configuration in the Nuxt setup.

Also even though vite is the default builder, design-wise Nuxt shouldn't depend its ecosystem and DX directly on a specific bundler (this way we can introduce new bundlers without huge migration costs like Nuxt 2 to Nuxt 3)

Working on a new nuxi dev server to implement a similar layer for shared WS listening on the same port of Nuxt and it keeps alive across Nuxt/Nitro/Builder restarts. Maybe it is something we could work on together.

**Comment by antfu** [comment]
That sounds great if Nuxt itself is going to have a WS server 👍. Changed the title

**Comment by bf** [comment]
I've spend considerable time figuring out websockets on nuxt a week ago, please have a look at: https://github.com/nuxt/nuxt/pull/19230

My proposal would be: untangle the whole websocket stuff from nuxt core/vite and just put a proxy in front of nuxt for your websocket needs. This fixes all docker port sharing issues and you have full control that the HTTP UPGRADE comand works.
