### ISSUE TITLE
@nuxt/devtools-kit not resolving from npm

### ISSUE THREAD

**Issue by Jamiewarb** [nuxt/devtools#143]
Hi there,

It looks like @nuxt/devtools-kit is not resolving from npm at the moment. [Following instructions from here](https://devtools.nuxtjs.org/module/utils-kit) for package name:

```
❯ pnpm add @nuxt/devtools-kit
 ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@nuxt%2Fdevtools-kit: Not Found - 404

This error happened while installing a direct dependency of <project>

@nuxt/devtools-kit is not in the npm registry, or you have no permission to fetch it.
```

**Comment by antfu** [comment]
It's not yet released. You can use `@nuxt/devtools-kit-edge` for now

**Comment by ManUtopiK** [comment]
Sorry, I can't reproduce the bug on stackblitz.com, I'll invest further...

**Comment by antfu** [comment]
Just released :)
