### ISSUE TITLE
[QUESTION] How to get and display the module options provided in the nuxt.config ? 

### ISSUE THREAD

**Issue by LouisMazel** [nuxt/devtools#148]
Hi,

In the devtools view of my module, I want display the current module options provided in the nuxt.config of the user. 

For example: My module [nuxt-well-known](https://github.com/zadigetvoltaire/nuxt-well-known)

The user provided the module options by an nuxt config entry:

```ts
export default defineNuxtConfig({
  modules: [
    '@zadigetvoltaire/nuxt-well-known'
  ],
  wellKnown: {
    ...
  } // <-- Module Options
})
```

How to get and display this config in the devtools module view ? 

```vue
<script setup lang="ts">
import { useDevtoolsClient } from '@nuxt/devtools/iframe-client'

const client = useDevtoolsClient()

const moduleOptions = // ??? <-- How to set it ? 
</script>

<template>
  <div class="relative p-10 n-bg-base flex flex-col h-screen">
    {{ moduleOptions }}
  </div>
</template>
```

Thanks for your work !

**Comment by antfu** [comment]
You could use:

```html
<script setup lang="ts">
import { useDevtoolsClient } from '@nuxt/devtools/iframe-client'

const client = useDevtoolsClient()

// Note: you might want to handle the await more properly
const nuxtConfig = await client.value!.devtools.rpc.getServerConfig()
const moduleOptions = nuxtConfig.wellKnown
</script>

<template>
  <div class="relative p-10 n-bg-base flex flex-col h-screen">
    {{ moduleOptions }}
  </div>
</template>
```

In the future, we will figure out a way to expose some composables to do them easier.

**Comment by LouisMazel** [comment]
Thank you a lot @Atinux and @antfu !

**Comment by Atinux** [comment]
Shall we document this @antfu?

**Comment by antfu** [comment]
It's "docuemented" in the type. As this is pretty advanced and not optimal. I would feel we should document it after we have something like:

```ts
const configRef = client.useServerConfig()
```
