### ISSUE TITLE
VS Code tab not working

### ISSUE THREAD

**Issue by thomasbnt** [nuxt/devtools#150]
Hello! 

I've got my WSL2 installed on my W10, but the _VS Code_ tab not working on devtools.

![devtools with VS Code tab opened](https://user-images.githubusercontent.com/14293805/226937073-b03fc40c-3eef-48b2-9630-0d6fcea7317b.png)

```bash

  System:
    OS: Linux 5.10 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 23.56 GB / 25.02 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
```

Tested directly with the debugger of Code v1.76.2 and with Webstorm v2022.3.4.

**Comment by antfu** [comment]
I cannot help as the given information is not sufficient. Please make sure you have `code-server` cli available in your environment.
