### ISSUE TITLE
Components detected as pages

### ISSUE THREAD

**Issue by ddahan** [nuxt/devtools#154]
I may use components into nuxt `pages` folder for organisation purpose.
In the example below, toolbox page is split between the actual page in `index.vue` and a component in `components/ToolboxToolTab.vue`

<img width="197" alt="image" src="https://user-images.githubusercontent.com/1933516/227661236-52cd2ba5-4a21-4f89-a94f-7efac8aa86d8.png">

However in this case, Nuxt dev tool will think the embedded component is a page and will propose a route:
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/1933516/227661363-31d95e4c-b12a-4610-a230-b30c4f186be7.png">

The route does not work, and trying to use it from dev tools seems to break a future navigation from the devtools.

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by ddahan** [comment]
Sure. I made [a Stackblitz](https://stackblitz.com/edit/nuxt-starter-mlcuh3?file=pages/index.vue) but devtools don't run with a `Failed to parse http message` error. Not sure why.

**Comment by antfu** [comment]
With your example, navigate to `/page2/components/ComponentForPage2`, it does show your component. So it's not "devtools think it's a page" but actually it **is** a page. You may move them out, or add them to `.nuxtignore`
