### ISSUE TITLE
"npx nuxi@latest devtools enable" not working on Microsoft Windows

### ISSUE THREAD

**Issue by AstragoDE** [nuxt/devtools#155]
Running `npx nuxi@latest devtools enable` does not work as expected on machines running Microsoft Windows.
The command adds the path of the project to the `~/.nuxtrc` file using backslashes (`\`) instead of forward slashes (`/`). This results in the Dev-Tools not being activated.
After manually changing the backslashes to forward slashes, everything works as expected.

### `~/.nuxtrc` Generated after running "npx nuxi@latest devtools enable" (NOT WORKING):
```
...
devtoolsGlobal.projects.0=C:\Programming\Nuxt\my-project
...
```

### `~/.nuxtrc` Expected after running "npx nuxi@latest devtools enable" (WORKING):
```
...
devtoolsGlobal.projects.0=C:/Programming/Nuxt/my-project
...
```

### System Information:
Tested on: 2023-03-25@15-20-44
Operating System: Microsoft Windows 11 Pro (22H2)
Used Shell: Microsoft PowerShell

**Comment by antfu** [comment]
It should be fixed in the latest version. If it still not working for you, please try to remove `~/.nuxtrc` and run it again. Thanks.
