### ISSUE TITLE
File is open in vi terminal instead of VS Code

### ISSUE THREAD

**Issue by ddahan** [nuxt/devtools#156]
When I use the feature to open a file directly from the dev tools, instead of opening the file in VS Code, the file is open into my VS Code terminal (the one where the server is run), using Vi:

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/1933516/227724626-d4141cb0-4eb6-472a-aa7b-50ca8073aaf4.png">

Thanks.

**Comment by antfu** [comment]
We are not able to help without enough information. Please report to https://github.com/yyx990803/launch-editor instead with more detailed reproductions. Thanks.
