### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by SaraVieira** [nuxt/devtools#157]
Heeey!

Tried to install the devtools today and got the following error:

<img width="949" alt="CleanShot 2023-03-25 at 18 11 39@2x" src="https://user-images.githubusercontent.com/1051509/227734324-eeee5b5c-65d6-40f2-9ef1-d19f5e610266.png">

Setup info:

- AMD Mac
-  "nuxt": "3.3.1"
- Node 18

Anyone else had this?

**Comment by robertlillipuu** [comment]
Nuxt Devtools is under heavy development. I tried with `nuxt@3.3.2` & `node@16` and worked. Within week there've been new releases - maybe could you try again?

**Comment by SaraVieira** [comment]
yap! it works on node 16 and 18 now!

Closing and thank you!
