### ISSUE TITLE
Assets tab causes freeze (too many assets)

### ISSUE THREAD

**Issue by Tigriz** [nuxt/devtools#158]
When opening assets tab in devtools and having many assets (1800 in my case, many in public folder), the whole devtools  or even the whole page freeze.
Maybe optimize it with lazy loading, or optionnally load public folder?

**Comment by arashsheyda** [comment]
Hi @Tigriz. you can now switch to `list view` to prevent freezing.
- you can change the view type by clicking on the button of top right corner

I've tested with a large number of assets (nearly 2300) on a laptop with an i3 processor and 6GB of RAM. I didn't experience any lag or freezing when using the list view.

https://github.com/nuxt/devtools/assets/38922203/b28509cf-c1af-442e-8cf0-9a9d3c93dd0b

I've closed the issue for now and If you see any freezing or any other problems, please let us know.
thanks
