### ISSUE TITLE
Nuxt won't start Cannot use 'in' operator to search for 'package' in pinia

### ISSUE THREAD

**Issue by therealokoro** [nuxt/devtools#165]
![image](https://user-images.githubusercontent.com/41494675/229854162-ca8176fe-0708-4269-9453-d9ed6064af73.png)

So this error comes up only when i try to use nuxt devtools

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by robertlillipuu** [comment]
@therealokoro Hi there! I took a look at your latest repository on your Github profile, and I saw that you have the following in [your config](https://github.com/therealokoro/staff-appraisal/blob/main/nuxt.config.ts#L8): 

```ts
export default defineNuxtConfig({
  // ...
  imports: { 
    dirs: ["stores"], 
    presets: ["pinia"], //  <-- This is causing problem.
  },
  // ...
})

```

I checked the Nuxt configuration API and seems there is not such property for *imports*: https://nuxt.com/docs/api/configuration/nuxt-config#imports

If this is not required or used by anything, then removing it would solve the issue.

**Comment by therealokoro** [comment]
@robertlillipuu. That's weird. It isn't in the docs.

![image](https://user-images.githubusercontent.com/41494675/230615487-1b673d43-8694-4365-8c2d-db6f9b907160.png)


![image](https://user-images.githubusercontent.com/41494675/230615052-6ae90dc7-37f1-4495-91b5-af6abd71bbe1.png)

Take a look at the screenshot above. Note that the nuxt version as at the time of taking the screenshot here is v3.3.3.

You can see that the `presets` options is there and offers a few possible options you can choose from.

**Comment by therealokoro** [comment]
I did notice that it's the cause of the problem as mentioned by @robertlillipuu. Removing it fixes the issue.
