### ISSUE TITLE
Does not work when ssr: false

### ISSUE THREAD

**Issue by itsmohmans** [nuxt/devtools#173]
I've tried installing Nuxt DevTools multiple times on [this project](https://github.com/itsmohmans/PomoDo) where server-side rendering is disabled on project-level, it installs correctly and when I run `npm run dev` it show `✔ Nuxt Devtools is enabled v0.3.2[global] (experimental)` but when I open the devtools it shows this 404 error 

![image](https://user-images.githubusercontent.com/55551984/230981106-a01352a9-949a-4cf8-a7c7-e5867d71fbb4.png)

_**I installed nuxt devtools the same way on a server-side rendered project and it worked correctly.**_

### Development environment
- Manjaro Linux `22.1.0`
- node `v18.12.1`
- npm `v8.19.2`
- nuxt `v3.1.2`

### How to reproduce
1. clone the project: `git clone https://github.com/itsmohmans/PomoDo.git`
2. install packages: `npm i`
3. enable nuxt devtools: `npx nuxi@latest devtools enable`
4. run the nuxt server: `npm run dev`

**Comment by antfu** [comment]
Can you narrow it down to a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thank you

**Comment by itsmohmans** [comment]
so I've created a new nuxt@3.1.2 project and set `ssr: false` in the configs, and the devtools worked fine so apparently it's not a problem with `ssr: false` but it's problem with the specific project above.    
I can't pinpoint what the issue is right now, but I'll update the comment once I find out

**Comment by itsmohmans** [comment]
Update:

It worked after I did the following:

1. removed `@vite-pwa/nuxt` module from nuxt.config.ts and `npm uninstall @vite-pwa/nuxt`
2. `npx nuxi@latest devtools enable` then `npm run dev` and it worked

**Comment by nicolaswalcker** [comment]
Hi, is there a way to use nuxt devtools together with the @vite-pwa/nuxt module?

**Comment by BayBreezy** [comment]
I am having a similar issue when i add the @vite-pwa/nuxt module.

the devtool breaks. is there any workaround for this? @antfu
