### ISSUE TITLE
Display Middleware for Pages

### ISSUE THREAD

**Issue by Atinux** [nuxt/devtools#184]
Could be between name and Layout ideally
![CleanShot 2023-04-15 at 18.00.22@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_04_15_at_18_00_22_2x_72b04637b4.png)

Note that a page can have multiple middleware, as well as anonymous one.

There are also global middleware, maybe we could list them around here:
![CleanShot 2023-04-15 at 18.03.27@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_04_15_at_18_03_27_2x_f45a941579.png)

Happy to know your thoughts @antfu

**Comment by antfu** [comment]
You mean "Display Middleware for Pages", right? 👀
