### ISSUE TITLE
​It's not working when I use nginx proxy port.​

### ISSUE THREAD

**Issue by moyukingS** [nuxt/devtools#193]
It just says' WebSocket disconnected '

I know this happens when I use vite, but vite can set up the hmr port

So will 'nuxt-devtool' support this as well?

**Comment by AwesomeAnders** [comment]
I have the same issue. I'm running a dev server through WSL2 with nginx and in the console i get the error: 

`bSocket connection to 'wss://_mydomain_/__nuxt_devtools__/entry' failed: 
I`

**Comment by antfu** [comment]
This will be fixed once https://github.com/nuxt/devtools/issues/112 get implemented.
