### ISSUE TITLE
Caching problem after initial routes scan in server-routes

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/devtools#204]
Currently, in the server-routes, after the initial routes scan, any new routes created are not shown in server-routes
is it a good idea to add a clear-cache button so user can manually re-scan the routes or we could clear the cache whenever a new route is added(does nitro has a hook like that?)

**Comment by antfu** [comment]
Yes, we need to watcher to get the updates from the FS, which we haven't implemented, I think. PR is welcome if you want to work on it.

Meanwhile, @pi0 made the open API entry point in https://github.com/unjs/nitro/pull/1162, which we could leverage later.
