### ISSUE TITLE
Types error 

### ISSUE THREAD

**Issue by Celibioux** [nuxt/devtools#206]
Does anyone see this error ? or just me idk what caused the issue as it was working fine 
Nuxt version : 3.4.3
Node 18.16.0
OS : Windows and Linux
![devtools](https://user-images.githubusercontent.com/33708072/235285272-f7f8f9b4-2fa9-4d2e-b6d4-eeb239367c73.png)

**Comment by antfu** [comment]
Please changed to 

```ts
devtools: {
  enabled: true
}
```

Instead.
