### ISSUE TITLE
Add support for other frameworks

### ISSUE THREAD

**Issue by Jak2k** [nuxt/devtools#223]
Other frameworks have the same problems, which has been the reason for creating these devtools. Maybe it is possible to make the nuxt-devtools modular so that other frameworks can adopt them.

**Comment by antfu** [comment]
The whole Nuxt DevTools is built on top of Nuxt's convention, it has to be some extent of the coupling to make something useful. For us, we don't have enough bandwidth to support other frameworks but we see there are already community forks/ports made possible: https://github.com/webfansplz/vite-plugin-vue-devtools

Thanks for bringing this up.

**Comment by Jak2k** [comment]
Thanks for the fast answer.

I opened an issue in the fork/port: https://github.com/webfansplz/vite-plugin-vue-devtools/issues/6
