### ISSUE TITLE
how to open this Project!

### ISSUE THREAD

**Issue by a137264832** [nuxt/devtools#225]
when i clone this project. 
i run "pnpm i".
then throw a error.
`│ packages/devtools-kit dev:prepare$ nr stub
│ packages/devtools-wizard dev:prepare$ nr stub
│ packages/devtools-kit dev:prepare: > @nuxt/devtools-kit@0.4.6 stub D:\GitHub-product\devtools\packages\devtools-kit
│ packages/devtools-kit dev:prepare: > unbuild --stub
│ packages/devtools-wizard dev:prepare: > @nuxt/devtools-wizard@0.4.6 stub D:\GitHub-product\devtools\packages\devtools-wizard
│ packages/devtools-wizard dev:prepare: > unbuild --stub
│ packages/devtools-kit dev:prepare: ℹ Stubbing @nuxt/devtools-kit
│ packages/devtools-wizard dev:prepare: ℹ Stubbing @nuxt/devtools-wizard
│ packages/devtools-wizard dev:prepare: Done
│ packages/devtools-kit dev:prepare: Done
│ packages/devtools dev:prepare$ nuxi prepare client
│ packages/devtools dev:prepare: Nuxi 3.4.3
│ packages/devtools dev:prepare:  ERROR  Error while requiring module ~/modules/markdown: SyntaxError: Unexpected token '||='
│ packages/devtools dev:prepare:  ERROR  Unexpected token '||='
│ packages/devtools dev:prepare:   nuxt.options.imports.transform ||= {};
│ packages/devtools dev:prepare:   ^^^
│ packages/devtools dev:prepare:
│ packages/devtools dev:prepare:   SyntaxError: Unexpected token '||='
│ packages/devtools dev:prepare:   at new Script (vm.js:102:7)
│ packages/devtools dev:prepare:   at createScript (vm.js:262:10)
│ packages/devtools dev:prepare:   at Object.runInThisContext (vm.js:310:10)
│ packages/devtools dev:prepare:   at jiti (D:\GitHub-product\devtools\node_modules\.pnpm\registry.npmmirror.com+jiti@1.18.2\node_modules\jiti\dist\jiti.js:  
│ packages/devtools dev:prepare:   at requireModule (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.4.3/node_modules/@nux  
│ packages/devtools dev:prepare:   at normalizeModule (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.4.3/node_modules/@n  
│ packages/devtools dev:prepare:   at installModule (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.4.3/node_modules/@nux  
│ packages/devtools dev:prepare:   at initNuxt (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+nuxt@3.4.3_nm6rzvbyritdhcm4ibr4bvmpd4/  
│ packages/devtools dev:prepare:   at async loadNuxt (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+nuxt@3.4.3_nm6rzvbyritdhcm4ibr4b  
│ packages/devtools dev:prepare:   at async loadNuxt (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+@nuxt+kit@3.4.3/node_modules/@nu  
│ packages/devtools dev:prepare:   at async Object.invoke (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+nuxi@3.4.3/node_modules/nux  
│ packages/devtools dev:prepare:   at async _main (/D:/GitHub-product/devtools/node_modules/.pnpm/registry.npmmirror.com+nuxi@3.4.3/node_modules/nuxi/dist/c  
│ packages/devtools dev:prepare: Failed
│ undefined`
ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @nuxt/devtools@0.4.6 dev:prepare: `nuxi prepare client`

**Comment by antfu** [comment]
You need to upgrade your Node.

And please, [learn a bit about how to ask questions / open issues](https://opensource.guide/how-to-contribute/#communicating-effectively) first.
