### ISSUE TITLE
Show `useSeoMeta` instead of `useHead` for open graph

### ISSUE THREAD

**Issue by Atinux** [nuxt/devtools#226]
![CleanShot 2023-05-10 at 18.22.04@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_05_10_at_18_22_04_2x_2a7fb6a11f.png)

**Comment by antfu** [comment]
Fixed https://github.com/nuxt/devtools/commit/f7d11ee39f97baa9f6a3793aa8e7c329d0f19e94
