### ISSUE TITLE
Vue Inspector shortcut doesnt work

### ISSUE THREAD

**Issue by sondh0127** [nuxt/devtools#234]
My shortcut to toggle the vue inspector doesn't work with devtool enabled

<img width="757" alt="image" src="https://github.com/nuxt/devtools/assets/62163604/a76f5ecb-26ee-491d-8ce5-29492c571eac">

**Comment by antfu** [comment]
We disabled the builtin shortcut to take full control on top of it. How often do you see yourself using the shortcuts? I think we might be able to proxy it, but my concern is that cmd+shift could be a bit to general

**Comment by sondh0127** [comment]
Every time I want to make a change to a page, I press this shortcut

**Comment by antfu** [comment]
In the next release, you will be able to override custom shortcuts like https://github.com/nuxt/devtools/blob/3311f11b7e1393cdab8a01cf647c86a6a79c584b/packages/devtools/client/nuxt.config.ts#L36-L40

Command + Shift is too general, and might conflicts with other shortcuts, thus we didn't enable it by default.

Thanks for bringing this up.
