### ISSUE TITLE
Issue installing devtools via a module

### ISSUE THREAD

**Issue by jpsc** [nuxt/devtools#235]
### Environment

- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.3`
- Nitro Version:    `2.4.0`
- Package Manager:  `npm@9.6.2`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/jpsc/beta.11.bug 

### Describe the bug

I'm adding `@nuxt/devtools` inside of a module with kit's `installModule` and it doesn't seem to work properly.
If I add the via the `nuxt.config` on the playground it works, but inside of the module not really.

### Additional context

When adding `@nuxt/devtools` via `installModule`

`addImports` is called here: https://github.com/nuxt-modules/i18n/blob/next/src/module.ts#L354

But the hook `imports:extend` is not called: https://github.com/nuxt/nuxt/blob/main/packages/kit/src/imports.ts#L9

### Logs

One of the errors is:

> Cannot read properties of undefined (reading 'Symbol(vue-i18n-routing-gor)')

This is just because the other module loaded is `nuxt-i18n`

**Comment by antfu** [comment]
Wonder why would you like to install it programmatically? DevTools relies on certain installed order, which is not really designed to be installed via `installModule`

**Comment by jpsc** [comment]
Ok, that explains why it might have issues using installModule.

Let me try to explain my use case and if Devtools is not meant to cater to this it's totally fine.

We have a rather large application, not so much in terms of code but in the number of teams/stakeholders. 
A long time ago, decided to split the application into different individual Nuxt applications per domain.
To keep consistent APIs and UI we created a Nuxt module (in Nuxt 2) that installs all required tools for multiple teams. 
This includes required modules (like nuxt-i18n or Tailwind), default configs, 3rd party scripts, auth, and much more.

This worked really well for us and now we are migrating everything to Nuxt 3. Devtools fits into the category of sharable default settings for us, so we are trying to get them on all projects by default, thus installing it via a module.

Does it make sense? Thanks

**Comment by antfu** [comment]
I wonder if

```ts
nuxt.options.devtools ||= {}
nuxt.options.devtools.enabled = true
```

Would work for you? Since Nuxt 3.4, it will install DevTools automatically once the option is set to true

**Comment by jpsc** [comment]
Yes, that seems to work/fix it 👍

Typescript doesn't like it though:

```ts
nuxt.options.devtools ||= {} // Type '{}' is not assignable to type 'boolean | { enabled: boolean; }'.
nuxt.options.devtools.enabled = true // Property 'enabled' does not exist on type 'false'.
```

**Comment by jpsc** [comment]
No, it doesn't work, it messes with other `#imports`.  I used this because auto-imports are disabled on modules.

**Comment by arashsheyda** [comment]
@jpsc can you try this:
```ts
const { resolvePath } = createResolver(import.meta.url)

await installModule(await resolvePath('@nuxt/devtools'), {
  enabled: true
})
```

this works for me

**Comment by arashsheyda** [comment]
@jpsc can you make it async?

```ts
async setup (options: ModuleOptions, nuxt: Nuxt) {

    await installModule('@nuxtjs/i18n', { 
        ...
    })

    await installModule('@nuxt/devtools', { enabled: true })
}
```

did work for me
![image](https://github.com/nuxt/devtools/assets/38922203/b7d40e03-609b-484c-a2a7-f5fd377e436c)

**Comment by jpsc** [comment]
Yes, this works 👍
Thank you.
