### ISSUE TITLE
Is it possible to change the iframe url?

### ISSUE THREAD

**Issue by 5v3n-08** [nuxt/devtools#237]
We are currently using a proxy in our project, https://example.com is running another project and https://example.com/next is running the current project with nuxt 3.

By default the iframe calls https://example.com/__nuxt_devtools__/client/ which redirects to the other project. 

Is it possible to change the url to https://example.com/next/__nuxt_devtools__/client/ without changing our proxy?

**Comment by antfu** [comment]
Do you have `baseUrl` set up? This sounds like a bug as the DevTools module should respect base URL.

**Comment by 5v3n-08** [comment]
yes i have set this in nuxt.config.ts

` app: {
    baseURL: '/next/'
  }`

**Comment by 5v3n-08** [comment]
What about the error? Do you already know when you can fix it?

**Comment by cpreston321** [comment]
Looks like it would need to prepend the baseUrl from nuxt if set on the main project. By default it will be set to `/__nuxt_devtools__/client` without the baseUrl from parent project.

Code: https://github.com/nuxt/devtools/blob/dfff5346ff57c0d4487b72ef96eb489349766831/packages/devtools/src/runtime/plugins/view/client.ts#L92
