### ISSUE TITLE
Devtools in defineNuxtConfig give type error

### ISSUE THREAD

**Issue by ThimoDEV** [nuxt/devtools#242]
![image](https://github.com/nuxt/devtools/assets/68739517/382ea172-6ef3-4330-b8e2-941e5752823d)

After succesfully installing nuxt devtools through setting the boolean flag in the nuxt.config.ts file, it gives the above type error. 

Steps to reproduce:

- Install nuxt devtools through setting boolean in config
- Run dev
- Optionally restart typescript server to trigger issue

Workaround: 

- Setting devtools: {} solves the issue, but this is quite confusing to see if devtools is enabled or not (or will be enabled based on an .env variable)

Nuxt version: 

3.4.2 and 3.5

**Comment by antfu** [comment]
This should be fixed in the latest wizard. Instead you can use

```ts
devtools: {
  enabled: true
}
```
