### ISSUE TITLE
Feature Request - Components tab showing App Tree

### ISSUE THREAD

**Issue by TechAkayy** [nuxt/devtools#244]
Is it possible to show the App tree (like in the browser/standalone vue-devtools) like how the nuxt-devtools inspired vue-devtools-vite-plugin has implemented? More details here - https://medium.com/@webfansplz_45104/introducing-vue-devtools-vite-plugin-1712f5dbebf2. Thanks in advance. 

![image](https://github.com/nuxt/devtools/assets/73772701/69b2ccf7-e647-4178-9285-319fb540c414)

**Comment by antfu** [comment]
Yeah, I think that makes sense. PR is welcome if someone wants to draft one.

**Comment by arashsheyda** [comment]
resolved in #655

**Comment by TechAkayy** [comment]
Thanks a bunch for implementing this 💚
