### ISSUE TITLE
When I do npx nuxi@latest devtools enable  

### ISSUE THREAD

**Issue by lmq352489099** [nuxt/devtools#248]
'devtools' is not an internal or external command or a runnable program

Or batch file.

How to deal with it?0.0

-------------------------
my pagejson
  "dependencies": {
    "@nuxtjs/color-mode": "^3.2.0",
    "@nuxtjs/tailwindcss": "^6.6.6",
    "@pinia/nuxt": "^0.4.10",
    "@prisma/client": "^4.11.0",
    "@types/jsonwebtoken": "^9.0.2",
    "bcryptjs": "^2.4.3",
    "dayjs": "^1.11.7",
    "gray-matter": "^4.0.3",
    "jsonwebtoken": "^9.0.0",
    "pinia": "^2.0.36",
    "remark": "^14.0.2",
    "remark-html": "^15.0.2"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.39.2",
    "@huntersofbook/naive-ui-nuxt": "^0.7.1",
    "@iconify-json/logos": "^1.1.31",
    "@types/bcryptjs": "^2.4.2",
    "@types/node": "^18",
    "@unocss/nuxt": "^0.52.3",
    "eslint": "^8.41.0",
    "nuxt": "3.2.2",
    "prisma": "4.14.1",
    "sass": "^1.62.0",
    "typescript": "^5.0.4"
  }

**Comment by lmq352489099** [comment]
> 'devtools' 不是内部或外部命令，也不是可运行的程序
> 
> 或者批处理文件。
> 
> 怎么处理？0.0

  "dependencies": {
    "@nuxtjs/color-mode": "^3.2.0",
    "@nuxtjs/tailwindcss": "^6.6.6",
    "@pinia/nuxt": "^0.4.10",
    "@prisma/client": "^4.11.0",
    "@types/jsonwebtoken": "^9.0.2",
    "bcryptjs": "^2.4.3",
    "dayjs": "^1.11.7",
    "gray-matter": "^4.0.3",
    "jsonwebtoken": "^9.0.0",
    "pinia": "^2.0.36",
    "remark": "^14.0.2",
    "remark-html": "^15.0.2"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^0.39.2",
    "@huntersofbook/naive-ui-nuxt": "^0.7.1",
    "@iconify-json/logos": "^1.1.31",
    "@types/bcryptjs": "^2.4.2",
    "@types/node": "^18",
    "@unocss/nuxt": "^0.52.3",
    "eslint": "^8.41.0",
    "nuxt": "3.2.2",
    "prisma": "4.14.1",
    "sass": "^1.62.0",
    "typescript": "^5.0.4"
  }

**Comment by antfu** [comment]
Can't reproduce. Can you try `npx nuxi@latest -v` and see what does it outputs?

**Comment by lmq352489099** [comment]
> 无法重现。你能试试看`npx nuxi@latest -v`它输出什么吗？
This is a display of the output
![image](https://github.com/nuxt/devtools/assets/37898934/81837e78-e6ec-46ec-9095-19dd179031fc)

**Comment by antfu** [comment]
It's 3.5.3 already, you should check your cache or anything why causing it not having the latest version

<img width="329" alt="image" src="https://github.com/nuxt/devtools/assets/11247099/b36a566b-e1e2-4a83-a6e3-6199aafe2de0">
