### ISSUE TITLE
Server routes from modules not showing in devtools

### ISSUE THREAD

**Issue by trc-mathieu** [nuxt/devtools#252]
Hey, I created a module and exposed the routes using `addServerHandler`. When accessing the Server Route page in devtools, I only see the routes from my app. It would be nice to be able to see the ones existing in modules as well.

Thanks!

**Comment by arashsheyda** [comment]
@antfu Do you think is it a good idea to switch to route list from `_nitro/openapi.json`?

**Comment by antfu** [comment]
@arashsheyda Yes, please, if you want to work on that :)

**Comment by arashsheyda** [comment]
@antfu Sorry for taking your time but on second tought, how can we access to the route's filepath?
