### ISSUE TITLE
Devtools fails to load when adding the `require-trusted-types-for 'script'` CSP directive

### ISSUE THREAD

**Issue by GalacticHypernova** [nuxt/devtools#254]
When adding devtools to the project and having the `require-trusted-types-for 'script'` CSP directive, upon the starting of the project it the console will log the `TrustedHTML` error. This also errors as soon as the app loads, no navigation needed.

**Comment by antfu** [comment]
It should be fixed with https://github.com/nuxt/devtools/issues/463, otherwise, please feel free to create a new issue with a minimal reproduction. Thanks.
