### ISSUE TITLE
adding options of pakage manegers when installing modules

### ISSUE THREAD

**Issue by Gianthard-cyh** [nuxt/devtools#263]
installing modules is currently using npm, but it will be better to show  something like a dialog before running the scripts for users to choose the pakage manager they want to use.

![image](https://github.com/nuxt/devtools/assets/45843411/e7aeef8c-bdc5-4c8a-bcdf-6839472fd9e6)

**Comment by Gianthard-cyh** [comment]
May add a global option for pakage managers

**Comment by Gianthard-cyh** [comment]
It seems that devtools is based on nypm, which only supports three major pakage managers.
![image](https://github.com/nuxt/devtools/assets/45843411/a3686b61-04e8-462e-822a-27aec478dcab)
Is it possible to add a customise configuration to allow users user their own pakage managers like `cnpm`?

**Comment by arashsheyda** [comment]
@Gianthard-cyh you can change this by setting `"packageManager": "cnpm"` in your project's `package.json`file.

@antfu is it a good idea to have a option in user's setting to change this behaviour? what do you think

**Comment by antfu** [comment]
I think if needed, changes should be done in `nypm` instead of in devtools.
