### ISSUE TITLE
new floating panel hides side nav link

### ISSUE THREAD

**Issue by CareTiger** [nuxt/devtools#268]
the new floating panel hides nav link and it is not movable.
![floating panel](https://zkcmpwzbigjgwiesauro.supabase.co/storage/v1/object/public/temp/devtools%20floating%20panel.png)

**Comment by arashsheyda** [comment]
Can you help to provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by CareTiger** [comment]
not able to reproduce.
