### ISSUE TITLE
Cannot interact with touch events IOS

### ISSUE THREAD

**Issue by riderx** [nuxt/devtools#272]
I just updated to latest devtools.

i'm using Nuxt in simulator with Capacitor app and now i cannot open the pills or move it, it was working in v5.

<img width="416" alt="CleanShot 2023-06-15 at 17 56 45@2x" src="https://github.com/nuxt/devtools/assets/4084527/785d1db5-c59a-461c-8829-0d1c192a5027">

i think it's maybe because of the bottom position, can we set the position with safe area of set on side by default on mobile ?

**Comment by antfu** [comment]
It's interesting to know you are using DevTools on mobile. I will see what I can do about that.

**Comment by riderx** [comment]
usually in mobile having the inspector it's even harder to do, you need to use third party tool or open chrome device debug and safari one who are not same.
With devtool we have common interface for both devices
