### ISSUE TITLE
devtools won't close when using click outside to close

### ISSUE THREAD

**Issue by ThimoDEV** [nuxt/devtools#273]
![devtools bug](https://github.com/nuxt/devtools/assets/68739517/29b7e649-2fa6-411a-a076-0c5e5efb4ef2)

in the gif video above I click on the nuxt logo to close the devtools. When I hold my mouse button the devtools is closed, but then when I release my mousebutton the devtools open again. This only happens when enabling "close devtools when clicking outside"

**Comment by arashsheyda** [comment]
@ThimoDEV Can you help to provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thanks.

[Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

I think it should not be a problem in 0.6.1

**Comment by ThimoDEV** [comment]
https://github.com/ThimoDEV/nuxt-devtools-click-bug

I just installed the latest devtools version and the issue was almost solved. 

Steps to reproduce: 

- Open Devtools panel
- Enable: "Close devtools when clicking outside" in settings panel
-  Disable: "Close devtools when clicking outside" in settings panel
- Enable: "Close devtools when clicking outside" in settings panel
- Notice the flag isn't working 

Additional context:

It seems like disabling the devtools panel with the button (below) reset the flag for clicking outside cause toggling the checkbox make the option work again.

![image](https://github.com/nuxt/devtools/assets/68739517/fb1a506d-e731-41c5-9cd8-056d25936b98)

Let me know if I can provide additional context, Thanks!

**Comment by arashsheyda** [comment]
it should be fixed now, thank you
