### ISSUE TITLE
Allow inspector open in editors other than vscode

### ISSUE THREAD

**Issue by yaquawa** [nuxt/devtools#281]
currently the only supported editor is vscode. I hope the inspector could open files in webstorm or phpstorm or other editors.

here is the major editors and their urls, just open the url by `window.location.href = URL`

```js
const EDITORS = {
  sublime: 'subl://open?url=file://{path}&line={line}&column={column}',
  textmate: 'txmt://open?url=file://{path}&line={line}&column={column}',
  emacs: 'emacs://open?url=file://{path}&line={line}&column={column}',
  macvim: 'mvim://open/?url=file://{path}&line={line}&column={column}',
  phpstorm: 'phpstorm://open?file={path}&line={line}&column={column}',
  webstorm: 'webstorm://open?file={path}&line={line}&column={column}',
  idea: 'idea://open?file={path}&line={line}&column={column}',
  vscode: 'vscode://file/{path}:{line}:{column}',
  'vscode-insiders': 'vscode-insiders://file/{path}:{line}:{column}',
  atom: 'atom://core/open/file?filename={path}&line={line}&column={column}',
}


```

**Comment by antfu** [comment]
It should. We are using https://github.com/yyx990803/launch-editor under the hood. If it doesn't work, please report upstream with reproductions. Thanks.

**Comment by yaquawa** [comment]
Hi @antfu , can't you reproduce this issue in your environment ? I have added `LAUNCH_EDITOR=phpstorm` to `.env.local`, but not works.

**Comment by antfu** [comment]
I don't use PhpStorm and don't have it installed. Nuxt DevTools does nothing specific than calling `launch-editor`, it shouldn't be an issue of DevTools unless you are able to prove it.

**Comment by yaquawa** [comment]
@antfu I tried in a fresh created project with `npx nuxi@latest init my-app`,and have my vscode opened, but the inspector won't open my source file. I also tried the `launch-editor`, it works fine.

**Comment by Smef** [comment]
It looks like the `LAUNCH_EDITOR` env gets overwritten by the `DEFAULT_INSPECTOR_OPTIONS` in `vite-plugin-vue-inspector`. In Vue Devtools Next we have to set the launchEditor config option like this:

```js
            VueDevTools({
                launchEditor: env.LAUNCH_EDITOR ?? false,
            }),
```

And it looks like we probably need to have the option added Nuxt Devtools as well, since it seems to. be implementing the same thing, which overwrites the env variable.

In vite-plugin-vue-inspector `/packages/core/src/index.ts:174`

**Comment by Smef** [comment]
It looks like the LAUNCH_EDITOR env changes are going to be part of 7.3, so it should be much easier to configure on a per-user basis using env values and `launchEditor` won't be necessary at all.

**Comment by Neoniq** [comment]
Tried today to make it open phpstorm, only way to make it work seems to add `"C:\Users\exie\AppData\Local\Programs\PhpStorm\bin\"` into path variable, then in your `.env` `LAUNCH_EDITOR = phpstorm64
`

Do not forget to reopen phpstorm completely

**Comment by skostadinov0141** [comment]
> Tried today to make it open phpstorm, only way to make it work seems to add `"C:\Users\{{USERNAME}}\AppData\Local\Programs\PhpStorm\bin\"` into path variable, then in your `.env` `LAUNCH_EDITOR = phpstorm64 `
> 
> Do not forget to reopen phpstorm completely

Can confirm it works in WebStorm too. In case you are using the ToolBox follow [this guide].(https://www.jetbrains.com/help/webstorm/working-with-the-ide-features-from-command-line.html#toolbox)

**Comment by Smef** [comment]
> Tried today to make it open phpstorm, only way to make it work seems to add `"C:\Users\{{USERNAME}}\AppData\Local\Programs\PhpStorm\bin\"` into path variable, then in your `.env` `LAUNCH_EDITOR = phpstorm64 `
> 
> Do not forget to reopen phpstorm completely

You can actually put the whole path in your LAUNCH_EDITOR env value (`export LAUNCH_EDITOR="idea"` in .zshrc on Mac/Linux, variables settings on Windows), and you shouldn't need to make the alias.

**Comment by Jakub-Horacek** [comment]
So how do I change the default editor of the Nuxt Devtools? Is it possible? I added the `LAUNCH_EDITOR=cursor` to my `.env`, but it seems like it is not enough.

**Comment by Smef** [comment]
You also need to make sure that you have the `cursor` cli command installed. From within the editor you can run the command `Shell Command: Install 'cursor' command` from the command pallete.

Separately, I'd recommend setting `export LAUNCH_EDITOR="cursor"` in your `.zshrc` or `.profile` or whatever your equivalent is, rather than putting it in the `.env` of a specific project. This

**Comment by lixiaofa** [comment]
> After doing the exact steps [@Smef](https://github.com/Smef) suggested, Nuxt Devtools is now opening the Cursor instead of VS Code, thanks a lot. 🫶

I can't open cursor either, except added the LAUNCH_EDITOR=cursor to my .env ， the cursor cli command installed.， Are there any other operations
@Jakub-Horacek

**Comment by Jakub-Horacek** [comment]
@lixiaofa Did you set `export LAUNCH_EDITOR="cursor"` in your `.zshrc` or `.profile` file?

**Comment by lixiaofa** [comment]
> [@lixiaofa](https://github.com/lixiaofa)您是否`export LAUNCH_EDITOR="cursor"`已在`.zshrc`或`.profile`文件中进行设置？

Yes, I have configured export LAUNCH_EDITOR="cursor" in both .env and .profile file. But it does not work

![Image](https://github.com/user-attachments/assets/b975aedc-3f8a-44fb-a609-f40c8ae3b171)

**Comment by Smef** [comment]
It looks like your configuration is correct, and it's attempting to launch the editor correctly, but there's an error when the editor is being launched through the CLI. Try manually launching the editor through the cli and see if you can get more details about what the editor is.

**Comment by lixiaofa** [comment]
> 您的配置似乎正确，并且正在尝试正确启动编辑器，但通过命令行界面 (CLI) 启动编辑器时出现错误。请尝试通过命令行界面手动启动编辑器，看看能否获取更多关于编辑器的详细信息。

Can you tell me how to do it?

**Comment by lixiaofa** [comment]
> It looks like your configuration is correct, and it's attempting to launch the editor correctly, but there's an error when the editor is being launched through the CLI. Try manually launching the editor through the cli and see if you can get more details about what the editor is.

To reproduce:
https://github.com/lixiaofa/nuxt-devtools-test.git

Can you help me try it?
Development environment: win11

**Comment by lixiaofa** [comment]
> 苹果。
> 
> 几个月前我确实遇到过类似你遇到的错误。运行 CLI 命令时出现了问题，不过你测试过之后似乎没有出现同样的错误。

@Smef  How did you solve it?

**Comment by smith558** [comment]
Anyone managed to set this up on WebStorm (in late 2025)?

**Comment by Smef** [comment]
@smith558 make sure you have the WebStorm CLI installed or you can use the full path to the app and you should have no problem!
