### ISSUE TITLE
Inspector doesn't bring up Editor when first load in 0.6.6

### ISSUE THREAD

**Issue by ifshizuku** [nuxt/devtools#298]
When the main DevTools interface is closed, **the inspector does not pop up the editor interface after I click on an element with the inspector**. When the main interface is open, clicking on the inspector closes the interface, and when I click on an element it shows up again, that's work properly.

The gif showed that: **The first time I clicked on the inspector while the main interface was closed, it did not make any interface changes after I clicked on an element.** The second time I clicked on it while the main interface was open, it worked properly.

![a](https://github.com/nuxt/devtools/assets/73536163/360cef9b-b4b5-4de9-9694-146fc00b44b4)

I wonder if this is intentional? I personally think it would be better to click on the inspector to pop up the edit page for the corresponding file directly, instead of opening the main interface first.

I added a change to the code about detecting the opening of the main interface and opening the editor page through the inspector while the main interface closed.

should i make a PR for it?

**Comment by antfu** [comment]
It's a regression made in the recent refactor. PR welcome, or I can fix it later

**Comment by ifshizuku** [comment]
i've submitted a PR

**Comment by ifshizuku** [comment]
it seems to face new issue in 0.6.6 while the RFC client implementation used: **The first time (or after hard reload) use the inspector** will not bring up the interface, but open main interface and **re-close** it, the inspector would be able to pop up the interface. @antfu 

![b](https://github.com/nuxt/devtools/assets/73536163/08d21dba-e4fb-420b-a62b-3157f58c2085)

not like the previous, it just need to load the interface once before to use Inspector

**Comment by AnotiaWang** [comment]
This issue remains in devtools v1.0

https://github.com/nuxt/devtools/assets/62269186/2f00d589-a9df-44a0-8351-08ebf6000d1d
