### ISSUE TITLE
fix(server-routes): Filter by Collection

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/devtools#308]
### 🐛 The bug

the current filter by colelction in server-routes put only the routes that are in a folder into a collection, example:

<details>
<summary>vscode</summary>

![image](https://github.com/nuxt/devtools/assets/38922203/977a1588-fecd-4b1c-a82f-18029d16a964)

</details>

<details>
<summary>devtools</summary>

![image](https://github.com/nuxt/devtools/assets/38922203/1ef218c9-2c29-46d3-b17f-4a9b54b337c3)
</details>

### 🛠️ To reproduce

n/a

### 🌈 Expected behavior

Is it a good idea to make it like this:

![image](https://github.com/nuxt/devtools/assets/38922203/845754df-df5e-4392-85fe-66da48cbd2dc)

**Comment by antfu** [comment]
Sounds good. I think we should have a button to toggle between tree/list views

**Comment by Atinux** [comment]
Sounds good to me too

**Comment by arashsheyda** [comment]
Sure!
