### ISSUE TITLE
feat: Close the devtools when clicking outside the devtools window

### ISSUE THREAD

**Issue by shakiroye** [nuxt/devtools#311]
### 🆒 Your use case

I often find myself needing to quickly close the devtools to focus on other elements or interact with my app. Currently, I need to either click the close button within the devtools or manually switch focus away from the devtools window.

With the proposed feature implemented, I would be able to simply click outside the devtools box to close it. It allows for a seamless transition between inspecting elements and interacting with my app.

### 🆕 The solution you'd like

An event listener that detects clicks outside the devtools box. When a click event occurs outside the devtools box, the event listener would trigger the devtools window to close.

**Comment by antfu** [comment]
We already have that feature :)
<img width="1384" alt="image" src="https://github.com/nuxt/devtools/assets/11247099/81cdc2f0-64df-4b14-8efb-6b7f39501a87">

**Comment by shakiroye** [comment]
Great!
