### ISSUE TITLE
feat: Automatic focus mode for the modules search input when the modules panel is opened

### ISSUE THREAD

**Issue by shakiroye** [nuxt/devtools#312]
### 🆒 Your use case

When opening the modules panel to search for a module, it would be convenient if the search input field was automatically focused. This would save developers an extra step of having to manually click on the input field before entering their search query.

### 🆕 The solution you'd like

When clicking on the "Install New Module" button and the modules panel is opened, set the focus on the search input field
![image](https://github.com/nuxt/devtools/assets/92779053/554284ac-56d6-4a7e-913f-470c4e9640a0)

**Comment by antfu** [comment]
Yeah indeed. PR welcome if you want to work on that :)

**Comment by shakiroye** [comment]
Okay, I am on it then!
