### ISSUE TITLE
Global inputs for server-routes

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/devtools#314]
### 🆒 Your use case

Sometimes, we require the ability to use the same input in different route or retain the input's value after restarting the server.

### 🆕 The solution you'd like

which of the following is better in terms of use?

<details>
<summary>method A: we can implent the global inputs with the local input and by clicking on add button user can select the type of input</summary>

![image](https://github.com/nuxt/devtools/assets/38922203/2fef4c06-ea6d-4950-870b-481fef86cfdd)

</details>

<details>
<summary>method B: we can implent the global inputs in a drawer and have all the global inputs in one place and user can select the inputs tab(query, params, e.g.) from there</summary>

![image](https://github.com/nuxt/devtools/assets/38922203/123742ce-f10c-46c6-a1cb-671d7a8a1244)

</details>

thanks

### ℹ️ Additional info

I think method B is more helful, maybe. method A is more beautiful though it can be a pain for someone that doesn't use global inputs, it needs to select local each time that wants to add input

**Comment by antfu** [comment]
I think we could go with method B and:

- Group by type, instead of selecting the type. So we will have multiple `Add` buttons in each section
- We could list global params in normal request's params with disabled state, to indicating they are inherit from the global state

**Comment by arashsheyda** [comment]
@antfu Sure! great idea, thanks
