### ISSUE TITLE
Server Routes Enhancement

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/devtools#322]
Here are some ideas to enhance the Server Routes Tab:

- [x] `Types tab`: after the response is returned, we can display a `types tab` in snippets or have the types tab near to response for easier selection. This tab would provide an type interface of our response
	- Use Case: For example this is good when we are sending request to a 3d party api
	- <details>
		<summary>Screenshort</summary>
		
		![image](https://github.com/nuxt/devtools/assets/38922203/c77f6235-2aae-4cd0-aa73-b4bb6835ce23)

	</details>
	
- [x] `Cookies tab`: This tab will show all the document cookies
- [ ] `Tests tab`: add simple tests as key, operation, value like.
	- Use Case: to make sure the response is returning as we desire
	- example: `ResponseCode`, `equals to`, `200`
	
- [ ] `CRUD generator tab`: We can have the option to generate routes directly from Devtools
	- Use Case: this would save time in some cases like when we want to have CRUD
	- <details>
		<summary>Screenshort</summary>
			
		This is en example of CRUD generator in `nxut-mongoose`, and beside generating routes, is generating schema files. I think we can have something like this
			
		![image](https://github.com/nuxt/devtools/assets/38922203/0a88ea61-9db3-4574-ab56-f51a99ee1819)
		
	</details>

**Comment by antfu** [comment]
1. That's a good idea! Tho I am not sure if we should generated them in house, maybe a generated link to services like https://app.quicktype.io/ so users could have more target languages to choice from
2. Sure
3. I think tests should be covered by proper tests but not relying on UI like DevTools. But maybe we could have a snippet tab to generate a test suite template?
4. I feel that might go about to far from Nuxt's scope. As even for CRUD, different project/company may have different conventions. I think it's better to leave it as 3rd party modules.

**Comment by arashsheyda** [comment]
@antfu sure, thank you

**Comment by antfu** [comment]
I consider this to be finished at the current scope (awesome work!). What do you think any other things missing?
