### ISSUE TITLE
Server Routes doesn't work

### ISSUE THREAD

**Issue by ReferTV** [nuxt/devtools#332]
### 📚 What are you trying to do?

I tried going into Server Routes and i got this:
![image](https://github.com/nuxt/devtools/assets/61411400/81913f41-6ee8-4705-95c9-cfdd50e9b47e)
![image](https://github.com/nuxt/devtools/assets/61411400/f930cffc-efac-4317-b1c1-1efae4f1f3b8)
![image](https://github.com/nuxt/devtools/assets/61411400/58c97756-9868-49a5-be3c-38845cd79146)

Until today everything was working normally, the problem suddenly appeared and I do not know what is causing it. I didn't update anything or do anything.

### ℹ️ Additional context

------------------------------
- Operating System: Windows_NT
- Node Version:     v16.17.0
- Nuxt Version:     3.6.3
- Nitro Version:    2.5.2
- Package Manager:  yarn@1.22.4
- Builder:          vite
- User Config:      ssr, devtools, modules, css, colorMode, experimental, nitro, runtimeConfig, delayHydration, routeRules, app
- Runtime Modules:  @nuxtjs/tailwindcss@6.8.0, @nuxtjs/color-mode@3.3.0, @nuxtjs/supabase@0.3.8, nuxt-icon@0.4.2, nuxt-delay-hydration@1.2.1
- Build Modules:    -
------------------------------

**Comment by ReferTV** [comment]
It seems that the problem occurs when I send too many requests to the API that does not return any data, because it does not work. The API returned a 404, I was making changes to the code because I was trying to fix it, and at some query this error appears. What I will say is that if I clear the project cache and the .nuxt folder it won't fix it, but to fix it, just clone the project anew from github, but let's not kid ourselves, this is not a solution to the problem.

**Comment by arashsheyda** [comment]
@ReferTV Can you share your projects link or a small reproduction? Thank you

**Comment by ReferTV** [comment]
![image](https://github.com/nuxt/devtools/assets/61411400/9f866f4e-59ea-4d22-92ee-b64d63eec5b9)
Generally it is unlikely to do anything, because as I say. This problem occurs randomly. When I cloned my project anew the problem disappeared, only that after a few days it suddenly returned when I was coding some new API file, after deleting this file the problem does not disappear, also as in the image attached above, maybe it is due to the fact that somewhere some key is saved, and after deleting the API file it remains?
