### ISSUE TITLE
feat: generate types from payload json

### ISSUE THREAD

**Issue by PatrikBird** [nuxt/devtools#339]
### 🆒 Your use case

Heyho :)

Just had an idea this morning...
When I want to create a type based on the data I've received. I've to do this manually or use an external service to speed up manual typing. It would be nice to include some sort of type generation that does this based on the input. 

### 🆕 The solution you'd like

A button within the `payload` tab that generates types as e.g. [quicktype](https://quicktype.io/typescript) does it.
The button could copy the generated type to clipboard.
<img width="634" alt="Screenshot 2023-07-22 at 13 16 25" src="https://github.com/nuxt/devtools/assets/52401692/eb7a8ca5-55d1-4ad5-aea8-3d85b8ca0543">

Not sure if feasible within the dev tools or not 😬 have a good day 🌞

### 🔍 Alternatives you've considered

Write the type manually or use a service like https://quicktype.io/typescript

**Comment by antfu** [comment]
Interestingly we already discussed about that: https://github.com/nuxt/devtools/issues/322#issuecomment-1643818818

/cc @arashsheyda

I am not yet sure if QuiteType support passing the text with URL params.

**Comment by arashsheyda** [comment]
@antfu can we use `quicktype-core` directly?

![image](https://github.com/nuxt/devtools/assets/38922203/0d1d8041-69d8-4fb3-ba23-1bcd85a30b10)
