### ISSUE TITLE
help: space in user name will break the opening process in vs code.

### ISSUE THREAD

**Issue by jesspinklet** [nuxt/devtools#345]
### 📚 What are you trying to do?

![image](https://github.com/nuxt/devtools/assets/77070946/e475cfe6-27f4-455d-b61a-48c1a506dac0)

My username in my OS has a space "mini op" and that will break some of the features of nuxt dev tools. 
Is there anyway to fix this or will I see an upcoming update for devtool to address this issue?

**Comment by arashsheyda** [comment]
It is a upstream issue [launch-editor/issues/35](https://github.com/yyx990803/launch-editor/issues/35) and has a workaround 

1. create a `.bat` file in a path with no spaces e.g. `C:\launch-editor.bat`
2. copy the code below to your .bat file
	```
	@echo off
	set filename=%1
	set lineNumber=%2
	set columnNumber=%3
	"%appdata%\..\Local\Programs\Microsoft VS Code\Code.exe" -r -g %filename%:%lineNumber%:%columnNumber%
	```
3. create a `.env` file in your project root and set `LAUNCH_EDITOR` value to you `.bat` path: `LAUNCH_EDITOR="C:\launch-editor.bat"`

for more info check [sveltejs/vite-plugin-svelte/issues/608](https://github.com/sveltejs/vite-plugin-svelte/issues/608)

**Comment by antfu** [comment]
Closing as this is an upstream issue, please keep track on https://github.com/yyx990803/launch-editor/issues/35. Thanks.
