### ISSUE TITLE
help: [vite-plugin-hot] Failed to import "/@vite/client"

### ISSUE THREAD

**Issue by zhaoweizhong** [nuxt/devtools#352]
### 📚 What are you trying to do?

I got this error when I opened the DevTools after installation by command:
<img width="943" alt="image" src="https://github.com/nuxt/devtools/assets/23146208/e0967e98-eb84-41eb-8c8d-e2a8ae28c9d9">
Seems to be a Vite-related error?

### 🔍 What have you tried?

- Tried reinstalling manually, but also didn't work.
- Checked the issues and there is no keyword related to this error.

### ℹ️ Additional context

- OS: macOS 13.5
- Node: 18.17.0
- Nuxt: 3.6.5
- @nuxt/devtools: 0.7.3
- Other modules: @pinia/nuxt, @arco-design/web-vue, mapbox-gl, @mapbox/mapbox-gl-geocoder, dayjs

**Comment by alice-njoroge** [comment]
I just converted my project from pure Vue 3 to Nuxt 3 and I also experienced the error until after I disabled devtools in nuxt.config.ts. Just posting this in case there is someone else stuck in a similar situation 
<img width="1108" alt="image" src="https://github.com/nuxt/devtools/assets/31002010/5d894b13-b262-4cc7-8a68-f01f9facf468">
