### ISSUE TITLE
fix: `requestForAuth` URL

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/devtools#355]
### 🐛 The bug

`nuxt.options.devServer.host` in requestForAuth rpc is returning `::`

### 🛠️ To reproduce

n/a

### 🌈 Expected behavior

it should return `localhost`

### ℹ️ Additional context

Is this nuxt related or can we use `nuxt.options.devServer.host === '::' ? 'localhost' : nuxt.options.devServer.host` instead of https://github.com/nuxt/devtools/blob/8ee0ae3f5f720d3674b6fa601be0545df020418b/packages/devtools/src/server-rpc/general.ts#L161

**Comment by antfu** [comment]
> nuxt.options.devServer.host === '::' ? 'localhost'

Yeah let's do it.
