### ISSUE TITLE
secure websocket

### ISSUE THREAD

**Issue by OverFlow636** [nuxt/devtools#37]
My nuxt app is served locally with ssl on a `.test` domain for sharing cookies with other projects. When I enabled devtools and clicked the icon in the bottom of my page i got an error about the websocket connection needing to be secure.

i was able to change ws to wss in my global module here, and then it worked perfectly
https://github.com/nuxt/devtools/blob/1c0f44c7474908b60bd12fbebc72432c60469a19/client/composables/rpc.ts#L27

can there be an option to detect/or configure this in the future?

**Comment by BobbieGoede** [comment]
I ran into the same issue, just opened a PR that should fix it here #36

**Comment by sifferhans** [comment]
Looks like this was merged!
