### ISSUE TITLE
Install VS Code Server when its running

### ISSUE THREAD

**Issue by cannap** [nuxt/devtools#38]
hi i am on windows 

When started vscode tunnel which is working it tells me its not running 

https://github.com/nuxt/devtools/blob/1c0f44c7474908b60bd12fbebc72432c60469a19/src/integrations/vscode.ts#L11

i am not sure this is the same as code-tunnel on windows 

```
npx which code-tunnel                                                                                                                                         
C:\Users\xxxx\AppData\Local\Programs\Microsoft VS Code\bin\code-tunnel.EXE
```

Tunnel started link also works:

![image](https://user-images.githubusercontent.com/1394151/217852986-84d95f3e-6105-4b58-a02b-2e65c0d435c3.png)

and anyway thanks for this awesome work

Vscode version:

![image](https://user-images.githubusercontent.com/1394151/217853633-3b547106-24c4-42c7-adb4-53626f280f95.png)

ok nvm i am not sure code tunnel is the same as a code server oO

**Comment by antfu** [comment]
Interesting, I didn't know it. I think it could be great to have an option to opt-in.

**Comment by cannap** [comment]
but i am not sure this is the same i also tried to rename and started it via cmd nuxt was catching up 

![image](https://user-images.githubusercontent.com/1394151/217877329-1c07ff5a-f556-4998-a0ad-aa0db08156af.png)
i just renamed code-tunnel to code-server  and started
but it still failed to connect in the iframe 
will give more infos later

**Comment by claranceliberi** [comment]
@cannap  I think you can try https://github.com/coder/code-server, however I am not sure if it runs on windows

**Comment by claranceliberi** [comment]
In the meantime I am going to work on support for code tunnel

**Comment by claranceliberi** [comment]
> In the meantime I am going to work on support for code tunnel

Anyway, this can't be achieved due to vscode.dev does not support iframe. And there is an open issue on their repo.

**Comment by antfu** [comment]
We have the features implemented now. But the current blocker is that `vscode.dev` is not allowing CORS iframe, so we probably need to stick to the local `code-server` for a while now. Closing as an upstream issue.
