### ISSUE TITLE
fix: [vite-plugin-hot] Failed to import "/@vite/client" when using nuxt.config "app/buildAssetsDir"

### ISSUE THREAD

**Issue by edgarrroussille** [nuxt/devtools#384]
### 🐛 The bug

Nuxt devtools doesn't load and console throws some errors, especially the `[vite-plugin-hot] Failed to import "/@vite/client"` one. Even after [this commit](https://github.com/nuxt/devtools/commit/b78d04f43ac5929047b5eb9e7db922b870e57777).

We're using a custom value for [buildAssetsDir](https://nuxt.com/docs/api/configuration/nuxt-config#buildassetsdir).

**Solution**: when commenting out this buildAssetsDir, everything works. So maybe just getting that value from config when loading the Vite client ? 

### 🛠️ To reproduce

https://stackblitz.com/edit/github-cwjhut?file=nuxt.config.ts

### 🌈 Expected behavior

Devtools should load even when using a custom `buildAssetsDir` path

**Comment by arashsheyda** [comment]
Hey @edgarrroussille, what version of devtools are you using? It should be fixed in the latest version #375

**Comment by cuebit** [comment]
@arashsheyda I'm encountering the same issue even on edge release that implements #375. I still observe the following error:

```
http://localhost:5314/_nuxt/@vite/client net::ERR_ABORTED 404 (Page Not Found: /_nuxt/@vite/client)
```

It appears `window.__NUXT__.config` evaluates to the following at the point of connection:
```json
{
    "baseURL": "/__nuxt_devtools__/client",
    "buildAssetsDir": "/_nuxt/",
    "cdnURL": ""
}
```

Yet evaluating the config in the browser equates to:
```json
{
    "baseURL": "/",
    "buildAssetsDir": "/customdir/",
    "cdnURL": ""
}
```

**Comment by edgarrroussille** [comment]
Hey @arashsheyda I'm using v0.7.6, same as in repro link

**Comment by arashsheyda** [comment]
Aww I found the problem, I will open PR as soon as possible. thanks

**Comment by cuebit** [comment]
> Aww I found the problem, I will open PR as soon as possible. thanks

Is it related to the window context? Perhaps the config is referring to the devtools window rather than the parent?

**Comment by arashsheyda** [comment]
> Is it related to the window context? Perhaps the config is referring to the devtools window rather than the parent?

exactly!

**Comment by cuebit** [comment]
> > Is it related to the window context? Perhaps the config is referring to the devtools window rather than the parent?
> 
> exactly! PR welcome if you want

Happy to spin up a PR later today 👍
