### ISSUE TITLE
点击后选择页面的元素，终端出现错误

### ISSUE THREAD

**Issue by sunpm** [nuxt/devtools#393]
<img width="550" alt="image" src="https://github.com/nuxt/devtools/assets/35005831/45824466-df5a-4065-a25b-88980438c7eb">
点击后选择页面的元素，终端出现错误：

```bash
Could not open DetailAdv.vue in the editor.                                                                             11:31:53 AM
The editor process exited with an error: spawn code ENOENT.                                                             11:31:53 AM

```

node 版本： v16.17.0

"nuxt": "^3.6.5",
"@nuxt/devtools": "latest",

**Comment by zcf0508** [comment]
用的是默认的 vscode 吗，如果不是的话可能需要配一下

https://github.com/webfansplz/vite-plugin-vue-inspector#--configuration-ide--editor

**Comment by zcf0508** [comment]
启动编辑器失败了，试试指定编辑器

https://github.com/yyx990803/launch-editor#custom-editor-support

**Comment by zcf0508** [comment]
https://github.com/nuxt/devtools/issues/345#issuecomment-1665100787

**Comment by sunpm** [comment]
> 启动编辑器失败了，试试指定编辑器
> 
> https://github.com/yyx990803/launch-editor#custom-editor-support

他是路径有空格导致的，错误码不一样，您可以正常打开编辑器吗

**Comment by zcf0508** [comment]
我用的 mac + code-insiders ，可以正常打开

**Comment by sunpm** [comment]
> 我用的 mac + code-insiders ，可以正常打开

我用的是英特尔mac+ webstorm or vscode 都无法打开

**Comment by sunpm** [comment]
> 我用的 mac + code-insiders ，可以正常打开

报这样的错误
<img width="869" alt="image" src="https://github.com/nuxt/devtools/assets/35005831/4fbe67f1-e18a-4a01-82bd-cbc673405a31">

**Comment by sunpm** [comment]
It's the same mistake that tried vue-tools.

**Comment by antfu** [comment]
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
