### ISSUE TITLE
fix: connect devtools to right dir when nuxtConfig.app.buildAssetsDir is customized

### ISSUE THREAD

**Issue by Sirkastik** [nuxt/devtools#399]
### 🐛 The bug

Nuxt Devtools can't load when `nuxtConfig.app.buildAssetsDir` is customized from the default `/_nuxt/`.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-gebsti?file=nuxt.config.ts

### 🌈 Expected behavior

Devtools should read the value from `app.buildAssetsDir` in Nuxt config and load properly.

**Comment by antfu** [comment]
Fixed by e28606a3a76b986ee35f73258783237ddad649aa, just released
