### ISSUE TITLE
unhandledRejection:  During On Click event on devtool icon.

### ISSUE THREAD

**Issue by mrniamster** [nuxt/devtools#41]
The below error is coming when i tried to click on the dev tool icon, it didn't crashed visually but got the below error in terminal,

System: Windows 10,

Nuxi 3.2.0                                                                                                              
Nuxt 3.2.0 with Nitro 2.2.1    

`ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'content')                                    22:29:25  

  at/node_modules/@nuxt/devtools/dist/chunks/index.mjs:11113:48
  at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
  at async Promise.all (index 0)
  at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
  at async checkForUpdateOf (/C://node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:8166:21)
  at async Promise.all (index 0)
  at async checkForUpdates (/C://projects/yts/node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:8184:19)`

**Comment by claranceliberi** [comment]
I think providing something like reproduction link could be useful @mrniamster

**Comment by mrniamster** [comment]
@manniL, @claranceliberi  Here is the reproduction demo for this issue:


https://user-images.githubusercontent.com/52563039/218290805-b0a2a98b-fc59-4a5f-9238-a7e4e5c510ff.mp4

**Comment by alexander-gekov** [comment]
@mrniamster  What node version are you using? I was having the same issue with node 14, but on version 16 or higher, it worked without errors.

**Comment by mrniamster** [comment]
@alexander-gekov  I'm using Node v18.

**Comment by gabrielcipriano** [comment]
I'm facing the same issue..

 `node 16.19`, `nuxt 3.2` with `devtools 0.1.2`

package.json dependencies:
`  "devDependencies": {
    "@commitlint/cli": "^17.4.2",
    "@commitlint/config-conventional": "^17.4.2",
    "@nuxt/devtools": "^0.1.2",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/tailwindcss": "^6.3.0",
    "@typescript-eslint/eslint-plugin": "^5.51.0",
    "@typescript-eslint/parser": "^5.51.0",
    "@vue/eslint-config-standard": "^8.0.1",
    "autoprefixer": "^10.4.13",
    "eslint": "^8.33.0",
    "eslint-plugin-vue": "^9.9.0",
    "husky": "^8.0.3",
    "lint-staged": "^13.1.1",
    "npm-audit-pipeline": "^0.6.1",
    "nuxt": "^3.2.0",
    "postcss": "^8.4.21",
    "prettier": "^2.8.3",
    "tailwindcss": "^3.2.4",
    "typescript": "^4.9.5",
    "vite-plugin-eslint": "^1.8.1"
  },
  "engines": {
    "node": "^16.19.0",
    "npm": "^8.19.0"
  }`

**Comment by mrniamster** [comment]
Thanks @antfu  Things are working great now :)
