### ISSUE TITLE
help: I can not pnpm install @nuxt/devtools

### ISSUE THREAD

**Issue by 2016WUJI01** [nuxt/devtools#410]
### 📚 What are you trying to do?

If i use npm/pnpm install @nuxt/devtools, it will have error with this 

`
.../node_modules/fast-folder-size postinstall$ node get-sysinternals-du.js
│ du64.exe not found at D:\Test\courseManage-Nuxt\node_modules\.pnpm\registry.npmmirror.…  
│ node:internal/url:611
│       throw new ERR_INVALID_URL(input);
│       ^
│ TypeError [ERR_INVALID_URL]: Invalid URL
│     at new NodeError (node:internal/errors:405:5)
│     at new URL (node:internal/url:611:13)
│     at new HttpsProxyAgent (D:\Test\courseManage-Nuxt\node_modules\.pnpm\registry.npmm…  
│     at exports.downloadDuZip (D:\Test\courseManage-Nuxt\node_modules\.pnpm\registry.np…  
│     at exports.default (D:\Test\courseManage-Nuxt\node_modules\.pnpm\registry.npmmirro…  
│     at Object.<anonymous> (D:\Test\courseManage-Nuxt\node_modules\.pnpm\registry.npmmi…  
│     at Module._compile (node:internal/modules/cjs/loader:1256:14)
│     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
│     at Module.load (node:internal/modules/cjs/loader:1119:32)
│     at Module._load (node:internal/modules/cjs/loader:960:12) {
│   input: '127.0.0.1:7890',
│   code: 'ERR_INVALID_URL'
│ }
│ Node.js v18.17.1
└─ Failed in 157ms at D:\Test\courseManage-Nuxt\node_modules\.pnpm\registry.npmmirror.com+fast-folder-size@2.2.0\node_modules\fast-folder-size
 ELIFECYCLE  Command failed with exit code 1.
`

May there have some problems with the package 'fast-folder-size' ?
My environment is windows 10 and  Node.js v18.17.1.

### 🔍 What have you tried?

If i use without @nuxt/devtools , it can run success.
My package.json 👇
`
{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "nuxt": "^3.7.0"
  }
}
`

**Comment by markthree** [comment]
#409 resolved this issue, you can try reinstalling the latest version of `@nuxt/devtools` @2016WUJI01
