### ISSUE TITLE
fix: Not working on WSL2

### ISSUE THREAD

**Issue by sebolio** [nuxt/devtools#415]
### 🐛 The bug

Apparently the server is listening to 127.0.0.1 instead of 0.0.0.0, so the website can't access it from the browser using 127.0.0.1.

### 🛠️ To reproduce

Have a PC with WSL2, connect to your Nuxt project and try to use the Devtools, check the console and see  errors

### 🌈 Expected behavior

Using http://127.0.0.1 should do the same as using http://localhost

**Comment by sebolio** [comment]
Note: I guess you all are Mac users, hence the "Cmd" icon on the search bar in your documentation, but you need to test it on WSL too, since it's what most developers use nowadays.

**Comment by Blaconix** [comment]
Can confirm this has been happening to me as well. 
I'm currently using `--host localhost` on my dev command and it seems to fix it.

**Comment by antfu** [comment]
This is a change in Nuxt 3.7 for security reasons. You can set `--host 0.0.0.0` to explicit listen to any requests.

**Comment by pi0** [comment]
localhost can be resolved to either `0.0.0.0` (IPv4) or `::1` (IPv6). Before 3.7, we were by default using all on network interfaces (basically same as `0.0.0.0`) but only **displaying*** localhost link.

BTW you normally wouldn't need this as WSL2 automatically proxies localhost ports to the host (windows).
