### ISSUE TITLE
help: is the sidebar uncollapse gone?

### ISSUE THREAD

**Issue by leochoo** [nuxt/devtools#416]
### 📚 What are you trying to do?

how can I uncollapse the devtool sidebar?

<img width="259" alt="CleanShot 2023-09-11 at 17 12 03@2x" src="https://github.com/nuxt/devtools/assets/26427048/d5fe546d-9dd9-49e0-9ad1-54e7f40e15b8">

**Comment by antfu** [comment]
Yes, it was redesigned, we will see how we could bring them back

**Comment by arashsheyda** [comment]
what are your thoughts about something like this?
- also what do you think about a option that options-out the overflow-tabs so user can scroll


https://github.com/nuxt/devtools/assets/38922203/dc3fb1e8-3ae5-4d1c-b42f-49b41e9aa726

**Comment by antfu** [comment]
@arashsheyda Looking quite nice! That was fast :) You can send a PR

**Comment by arashsheyda** [comment]
@antfu thanks :D sure
