### ISSUE TITLE
npx nuxi devtools enable corrupts old nuxt projects!

### ISSUE THREAD

**Issue by EternalC0der** [nuxt/devtools#42]
I executed `npx nuxi devtools enable` and it installed some kind of global package that stops `nuxt 2` projects from working!

I  tried uninstalling the global `@nuxt/devtools`  package and it still gives me errors (different one tho):

It gives me this error on my other (old) project:
```
 WARN  Module C:/Program Files/nodejs/node_modules/@nuxt/devtools/dist/module.mjs not found. Please ensure C:/Program Files/nodejs/node_modules/@nuxt/devtools/dist/module.mjs is in dependencies and installed.

 FATAL  Cannot find module 'C:/Program Files/nodejs/node_modules/@nuxt/devtools/dist/module.mjs'              22:28:55
Require stack:
- D:\Development\Repositories\cimaba\node_modules\@nuxt\core\dist\core.js

  Require stack:
  - node_modules\@nuxt\core\dist\core.js
  at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
  at Function.resolve (node:internal/modules/cjs/helpers:109:19)
  at _resolve (node_modules\jiti\dist\jiti.js:1:192796)
  at Resolver.jiti [as _require] (node_modules\jiti\dist\jiti.js:1:195025)
  at Resolver.requireModule (node_modules\@nuxt\core\dist\core.js:381:29)
  at ModuleContainer.addModule (node_modules\@nuxt\core\dist\core.js:182:38)
  at node_modules\@nuxt\utils\dist\utils.js:639:43
  at async ModuleContainer.ready (node_modules\@nuxt\core\dist\core.js:55:5)
  at async Nuxt._init (node_modules\@nuxt\core\dist\core.js:478:5)
  
  
✖ Nuxt Fatal Error
Error: Cannot find module 'C:/Program Files/nodejs/node_modules/@nuxt/devtools/dist/module.mjs'
 Require stack:
- D:\Development\Repositories\cimaba\node_modules@nuxt\core\dist\core.js
```

I tried deleting my `node_modules` and reinstalled everything, and it still doesn't work.
Also, there is no changes in my git, and it was working before installing the `@nuxt/devtools`

**Comment by jesspinklet** [comment]
Same here.
Some how this was globally enabled on an old nuxt 2 project and I have no idea how to remove or disable it.

**Comment by pi0** [comment]
You can remove from .nuxtrc in homedir as last resort.

/cc @antfu

**Comment by antfu** [comment]
A fix has been released, you can run `npx nuxi@latest devtools enable` again in any app (ensure it runs v0.1.2 or above), it should fix the entry to not break Nuxt 2 apps.

If you want to remove DevTools globally, now you can run `npx nuxi@latest devtools disable --remove`.

**Comment by alexkobrin** [comment]
Had the same issues. Worked for me  npx nuxi@latest devtools enable , and old nuxt 2 and nuxt 3 projects work correctly.  But I don't get how it me be conflicting with all nuxt project .

**Comment by johannessnakeware** [comment]
`npx nuxi@latest devtools disable --remove` didn't work for me

The conflict is being encountering by some lines in the .nuxtrc file. To resolve this, I removed the following lines from the `%userprofile%/.nuxtrc` file:

```
modules.0=C:/Program Files/nodejs/node_modules/@nuxt/devtools/module.cjs
devtoolsGlobal.projects.0={LOCATION_TO _YOUR_PROJECTS}
```
