### ISSUE TITLE
fix: can't connect to server (websocket connection fails)

### ISSUE THREAD

**Issue by jankaderabek** [nuxt/devtools#449]
### 🐛 The bug

Devtools doesn't work on my machine, it's stuck on `Connecting to server` and then shows `WebSocket disconnected`. I use base Nuxt 3 starter. The interesting thing is that when I run the starter template on Stackblitz it works, so it probably has to be connected to my machine, but really don't know how. Do you have any tips on how to debug it?

<img width="1512" alt="Snímek obrazovky 2023-09-28 v 9 16 08" src="https://github.com/nuxt/devtools/assets/7320529/d47d1f05-1652-48ed-9698-d3176c679370">

<img width="1512" alt="Snímek obrazovky 2023-09-28 v 9 28 18" src="https://github.com/nuxt/devtools/assets/7320529/6b3a9fab-1732-4b05-827e-be795690584f">

```
jankaderabek@Jan-MacBook-Pro test-devtools % node -v
v18.18.0
```

<img width="414" alt="image" src="https://github.com/nuxt/devtools/assets/7320529/dc6bd6df-d223-4206-a3c8-2fe30eda43c5">

<img width="706" alt="image" src="https://github.com/nuxt/devtools/assets/7320529/a407304e-4182-4090-9828-58f228e7f056">

The issue is same in every browser I have

### 🛠️ To reproduce

https://stackblitz.com/github/nuxt/starter/tree/v3/

### 🌈 Expected behavior

It should connect to devtools websocket server

**Comment by arashsheyda** [comment]
can you make sure that you are using the latest version of DevTools?

**Comment by jankaderabek** [comment]
Yep, I checked that, Nuxt version `3.7.4` and devtools `0.8.5`.

**Comment by antfu** [comment]
The devtools in the screenshot seems to be pretty old. Can you check `.nuxtrc` file under your home directory? There there is nuxt/devtools related entries, remove it and try restart your nuxt app.

**Comment by daver987** [comment]
I have this exact same issue.  There isn't a `.nuxtrc` in any of my projects.  It just started to do this after the last update.  The only difference is I have an M1 mbp. 

Here are some screenshots maybe they will give you some clues.


<img width="1360" alt="Screenshot 2023-09-29 at 9 28 49 AM" src="https://github.com/nuxt/devtools/assets/85001306/b3adbc14-b4d6-40a1-a3d6-e96e3f16c193">
<img width="1125" alt="Screenshot 2023-09-29 at 9 29 51 AM" src="https://github.com/nuxt/devtools/assets/85001306/b0887d83-bee8-4154-9ac2-77b4dc48ec3f">
<img width="596" alt="Screenshot 2023-09-29 at 9 30 30 AM" src="https://github.com/nux
<img width="1351" alt="Screenshot 2023-09-29 at 9 31 01 AM" src="https://github.com/nuxt/devtools/assets/85001306/cad8fdf6-00cf-47ac-8330-ecbbc5f7d9aa">
t/devtools/assets/85001306/dbd3b76e-d202-4677-9b76-8807562a0bd0">

**Comment by jankaderabek** [comment]
Ok I removed `~/.nuxtrc` and it started to work, I just noticed that in the console is a message about Nuxt devtools, now I can see correctly version 0.8.5. I was checking the version just in package-lock and node_modules before.

```bash
jankaderabek@Jan-MacBook-Pro drone-analysations % npm run dev

> dev
> nuxt dev

Nuxt 3.7.4 with Nitro 2.6.3                                                                                                                                           9:20:55 AM
                                                                                                                                                                      9:20:55 AM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using default Tailwind CSS file                                                                                                                   nuxt:tailwindcss 9:20:56 AM
✔ Nuxt DevTools enabled (v0.8.5), press Shift + Option + D in app to open  (experimental)                                                                            9:20:57 AM
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                                                                 nuxt:tailwindcss 9:20:57 AM
✔ Nitro built in 847 ms                                                                                                                                        nitro 9:21:00 AM
ℹ Vite client warmed up in 4091ms
```

Before it was:
```bash
jankaderabek@Jan-MacBook-Pro drone-analysations % npm run dev

> dev
> nuxt dev

Nuxt 3.7.4 with Nitro 2.6.3                                                                                                                                           6:31:06 PM
                                                                                                                                                                      6:31:07 PM
  ➜ Local:    http://localhost:3000/
  ➜ Network:  use --host to expose

ℹ Using default Tailwind CSS file                                                                                                                   nuxt:tailwindcss 6:31:08 PM
✔ Nuxt Devtools is enabled v0.2.5[global] (experimental)                                                                                                                18:31:08
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                                                                 nuxt:tailwindcss 6:31:08 PM
ℹ Vite client warmed up in 3826ms                                                                                                                                    6:31:13 PM
✔ Nitro built in 681 ms 
```

Everything work smoothly now 🎉 , thank you for this amazing module @antfu 👍

**Comment by jankaderabek** [comment]
@daver987 I can see in your console screenshot that you have devtools in version 0.4.2 (current is 0.8.5), try to find out why is that.

**Comment by daver987** [comment]
> @daver987 I can see in your console screenshot that you have devtools in version 0.4.2 (current is 0.8.5), try to find out why is that.

That's a good question, it always said it was up to date, I'll see if I can find out why.
