### ISSUE TITLE
Devtool button aria-label

### ISSUE THREAD

**Issue by joesobo** [nuxt/devtools#45]
Noticed while running a lighthouse test on my nuxt app. Seems like the button needs a aria-label?

Probably right here: https://github.com/nuxt/devtools/blob/489d99fa252ea85fbc2a3e0cb605b140d56ee9c2/src/runtime/plugins/view/Container.vue#L64

Happy to open a pr for this

![Screenshot 2023-02-09 at 5 35 51 PM](https://user-images.githubusercontent.com/26047842/217978243-2e465890-3970-46b2-8395-165c09820708.png)

**Comment by antfu** [comment]
Good catch. PR welcome!
