### ISSUE TITLE
Cannot start nuxt: The requested module 'vite-plugin-inspect' does not provide an export named 'default'

### ISSUE THREAD

**Issue by huongphamx** [nuxt/devtools#457]
### 🐛 The bug

After update packages with `pnpm update`, my local run cannot start Nuxt. The `pnpm run dev` claim that `Cannot start nuxt:  The requested module 'vite-plugin-inspect' does not provide an export named 'default' `.

I tried to reproduce on StackBlitz but devtools here still work. If I disable devtools, Nuxt can start again. Did anyone face same situation?

Dependencies:
![image](https://github.com/nuxt/devtools/assets/91840958/ef8811f3-d537-44fa-a079-bca6d2fdf776)

Terminal:
![image](https://github.com/nuxt/devtools/assets/91840958/f20e22e4-9298-4fbd-89fc-a303ace73beb)

### 🛠️ To reproduce

I can't reproduce on StackBlitz

### 🌈 Expected behavior

Nuxt can start with devtools enabled.

**Comment by the14thsky** [comment]
I'm facing this same thing too. Thanks for reporting.

**Comment by arashsheyda** [comment]
it's a upstream [issue](https://github.com/antfu/vite-plugin-inspect/issues/97)
a workaround for now is to disable `viteInspect`:
```ts
devtools: {
    enabled: true,
    viteInspect: false,
  },
```

**Comment by antfu** [comment]
Should be fixed
