### ISSUE TITLE
fix: since moving from 1.0.0-beta.2 to 1.0.0-beta.3 the devtools crashes after few seconds

### ISSUE THREAD

**Issue by itai-gendler** [nuxt/devtools#480]
### 🐛 The bug

once i moved from 1.0.0-beta.2 to 1.0.0-beta.3 every time i open the dev tools it crashes after a few seconds.

![image](https://github.com/nuxt/devtools/assets/16039521/0d1a02b8-605d-46ec-93a2-f05114e1fc71)

even after reloading it still crashes after few seconds. can't work with it at all.

i am using nuxt version 3.6.5 atm.

this also happens when moving to version 1.0.0.

i had to revert to continue using beta.2.

please advise what to do.

### 🛠️ To reproduce

-

### 🌈 Expected behavior

should not crash

**Comment by antfu** [comment]
Can you share a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example). Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
