### ISSUE TITLE
fix: devtools not opening in Nuxt with fresh installation

### ISSUE THREAD

**Issue by Ragura** [nuxt/devtools#488]
### 🐛 The bug

I just started a new Nuxt project using the standard installtion: `pnpm dlx nuxi@latest init <project-name>`
Trying to open the devtools gives the following error in the browser after a second or so of a black window popping up:
```
Vue warn]: Unhandled error during execution of native event handler 
localhost/:1 Uncaught (in promise) Nuxt Devtools client injection failed
```

I have tried using npm, pnpm and bun with the same results. Updating the package to the nightly channels for Nuxt and Devtools doesn't resolve the issue. Also downgraded Nuxt to 3.7.0 without success.
I'm using MacOS. Tested various browsers with same results.

The strange thing is it doesn't happen in Nuxt's Stackblitz template which I was trying to use for a reproduction. But as the "reproduction" is simply using nuxi to install a fresh project it seemed useless anyway.

### 🛠️ To reproduce

Simply start a new project: pnpm dlx nuxi@latest init <project-name>

### 🌈 Expected behavior

The Nuxt Devtools icon is there but clicking it only opens a black window and gives the error.

**Comment by Ragura** [comment]
I was able to fix it on my end by doing trying two things at the same time, which is a true sin as far as diagnosis goes. Now I don't know which of the two fixed it.
These are the two things I did:
1. Upgrade node from `18.14.0` to `18.18.0 (lts)`
2. Delete `~/.nuxtrc` which I got from this past issue: #50

I'll close the issue, but hopefully it can help others fix it if they encounter the same issue.

**Comment by husayt** [comment]
![image](https://github.com/nuxt/devtools/assets/1169324/3b052d61-a4c0-41ad-8c7e-a9f91e617835)


doesn't start for me with latest nuxt 3.9.0. I tried everything but nuxt devtools wuldn't start at all

**Comment by frank-topel-dbi** [comment]
I'm also getting this `Nuxt DevTools client injection failed` error, on MacOS Sonoma, Chrome Beta 129.0.6668.29, nuxt 3.13.0, Node 20.12.2, npm 10.8.2.

The error occurs since I installed the `@prisma/nuxt` package. That also keeps asking me 

```

Do you want to view and edit your data by installing Prisma Studio in Nuxt DevTools?
```

which is more than just annoying, because this question randomly re-pops while the dev server is running, and stops it from running until I answer the question. Neither choosing "yes" nor "no" changes this behaviour.

**Comment by martinszeltins** [comment]
This is also happening to me but only on `Chrome Beta`. It works in Chrome stable and it also works in Firefox. No clue why it doesn't work on Chrome Beta.
