### ISSUE TITLE
fix: Nuxt Devtools still uses the 0.2.2 version that crashes

### ISSUE THREAD

**Issue by TechWatching** [nuxt/devtools#490]
### 🐛 The bug

When running my application, nuxt devtool crashes (cf following error) and the panel is not displayed:
![image](https://github.com/nuxt/devtools/assets/15186176/c93aab61-5d49-47c4-a214-1167d85da37d)

Nuxt seems to be using a previous version of nuxt/devtools (0.2.3) even if my package.json indicates the nuxt/devtools 1.0.0 version.
![image](https://github.com/nuxt/devtools/assets/15186176/50a03dab-88a1-441a-b21f-7d7553ccd0dc)

![image](https://github.com/nuxt/devtools/assets/15186176/74a75cd3-84de-4cbf-921d-b9f649c1898a)

It seems that the 0.2.3 version was cached in the pnpm store for whatever reason is still the version used instead of the 1.0.0. It's only on one of my laptop, the issue does not happen on another laptop where I never used Nuxt DevTools

### 🛠️ To reproduce

Can't be repoduced on laptops that did not have the 0.2.3 devtools version installed

### 🌈 Expected behavior

Nuxt devtools is displayed on the page.

**Comment by antfu** [comment]
Can you check if you have a `.nuxtrc` file under your home dir? If so, you can try to remove it and restart the server to see if it helps

**Comment by TechWatching** [comment]
It worked. Thanks a lot. 🙏
