### ISSUE TITLE
fix: css class name misleading when using css modules other than unocss

### ISSUE THREAD

**Issue by DevDengChao** [nuxt/devtools#495]
### 🐛 The bug

I started a new Nuxt project and installed the https://nuxt.com/modules/tailwindcss module, when adding css classes, the IDE sugguest me there is a `w-100` class, then I added that class to an element but it does not works.

You can see the IDE found the .w-100 classes from devtools' `entry.xxxxxxxx.css`, but you cannot use it as tailwindcss dose not have such class:
![example](https://github.com/nuxt/devtools/assets/16363180/7c84a951-4db9-410a-b317-1915ba26533e)

### 🛠️ To reproduce

https://github.com/DevDengChao/nuxt-devtools-css-class-name-misleading-bug-report

### 🌈 Expected behavior

+ Exclude that file from IDE suggestion index ? (Maybe I should tweak my IDE, asked as [WEB-63569](https://youtrack.jetbrains.com/issue/WEB-63569/How-to-exclude-css-file-in-nodemodules-to-be-indexed)) 
+ Generate proper css files to enhance IDE suggestion ?

**Comment by antfu** [comment]
I am not sure how your question related to Nuxt DevTools. Can you elaborate more?

**Comment by DevDengChao** [comment]
Close as it is [a bug of WebStrom](https://youtrack.jetbrains.com/issue/WEB-55663) .
