### ISSUE TITLE
fix: Unable to connect devtools to Nuxt (3.5.2)

### ISSUE THREAD

**Issue by mateenmohsin** [nuxt/devtools#497]
### 🐛 The bug

I am trying to enable Devtool on Nuxt version **3.5.2**  using Yarn.
According to documentation Devtool is compatible with this version.
But it is in **retrying** state (Disconnected from Server).

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-shwpss

### 🌈 Expected behavior

Devtool should be enabled and working for Nuxt 3.5.2 version.

**Comment by desenvolvimento02jocc** [comment]
Same happens on 3.5.3

**Comment by ptolios** [comment]
Same on 3.6.5

**Comment by ptolios** [comment]
For me the problem was resolved after I ran
`yarn upgrade`

**Comment by EvgenyWas** [comment]
> For me the problem was resolved after I ran
> 
> `yarn upgrade`

Yes, for the latest version of Nuxt the devtools are working fine, but for us it's quite costly and we'd like to stay on the current version. It should be compatible with other versions as it's written in the doc.

**Comment by antfu** [comment]
This is because we are using a new Vite API to detect the connection status, where Nuxt 3.5.2 doesn't have the latest Vite available. It should be fixed in the next release
