### ISSUE TITLE
feat: Better VS Code Server documentation

### ISSUE THREAD

**Issue by nopeless** [nuxt/devtools#498]
### 🆒 Your use case

I found it a little confusing to install, as there exists concepts such as code tunnel which isn't the code-server the dev tools use. 

### 🆕 The solution you'd like

I think the link in the devtools should point to a different page which explains the difference between code server and code tunnel, and additionally link them to coder.com

**Comment by ennioVisco** [comment]
Yeah, I still can't figure how to make it work
