### ISSUE TITLE
help: Build Analyzer

### ISSUE THREAD

**Issue by localusercamp** [nuxt/devtools#499]
### 📚 What are you trying to do?

I enable Build Analyze in settings, but tab is not appearing, what am i doing wrong?
![image](https://github.com/nuxt/devtools/assets/45385480/e3bc68a2-692d-4ce9-ac82-659112b3759a)

### ℹ️ Additional context

Nuxt 3.8.
Devtools removed from dependensies and from modules (nuxt register it automatically).
Devtools config: 
```ts
{
  devtools: {
    timeline: {
      enabled: true,
    },
  },
}
```

**Comment by arashsheyda** [comment]
@localusercamp can you share a reproduction?

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by localusercamp** [comment]
> @arashsheyda, @antfu
> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.


Sorry for late response, i was busy.
[Reproduction](https://github.com/localusercamp/nuxt-devtools-build-analyzer-bug-reproduction).
Reproduction was made with `npx nuxi init <app>`. It is a fresh Nuxt 3 project, but tab do not appear.

**Comment by localusercamp** [comment]
I do not know what was the cause of the issue, but it is working fine now...

**Comment by tkjaergaard** [comment]
I'm also experiencing that the Build Analyze feature missing form the dev tools.

```json
{
  "dependencies": {
    "@nuxt/devtools": "latest",
    "nuxt": "^3.9.1",
    "vue": "^3.4.7"
  }
}
```
