### ISSUE TITLE
Multiple pages when clicking on "Go back home" button 

### ISSUE THREAD

**Issue by wJoenn** [nuxt/devtools#505]
### 🐛 The bug

There's a bug with `@nuxtjs/tailwindcss` that'll make the tailwind's viewer not work when accessing it from the devtool.
Once faced with the 404 we have a button to go back home which I assume should take me back to the devtool's home page.
It does indeed but while doing so it also open a nested devtool page and repeats this behaviour everytime the same button is clicked
![image](https://github.com/nuxt/devtools/assets/75388869/7ed16961-d21a-408a-827b-c8b0bc0ae473)

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-jwoekj?file=nuxt.config.ts

### 🌈 Expected behavior

I suppose it should just take me back to the homepage without opening an actual page.
Best behaviour would be to actually have access to Tailwind's viewer but I suppoe that an issue with `@nuxtjs/tailwindcss`

**Comment by antfu** [comment]
I am not sure if there is anything that can be done on the DevTools side. As we give an iframe to the custom tab, and how it renders is up to the module to control. I think it should be fixed on the tailwind module
