### ISSUE TITLE
iframe URL ignores baseURL

### ISSUE THREAD

**Issue by codehead** [nuxt/devtools#506]
### 🐛 The bug

Comments on issue #237 seem to indicate that PR #386 would allow the iframe to be relative to baseURL, but the iframe still points to `/__nuxt_devtools__/client/` - this makes nuxt devtools go 404 when the application is accessed through a reverse proxy.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-s8vyfn?file=nuxt.config.ts

### 🌈 Expected behavior

Setting baseURL=/prefix/ in nuxt.config.ts
```typescript
export default defineNuxtConfig({
  app: { baseURL: '/prefix/' },
  devtools: { enabled: true },
});
```
the iframe should point to `/prefix/__nuxt_devtools__/client/` but opening the browser's network monitor or DOM inspector will show that it still points to `/__nuxt_devtools__/client/`

**Comment by fabkho** [comment]
same for me!

**Comment by benje** [comment]
Also seeing a 404 when launching the dev tools. Fixing this would be super useful as we are currently unable to use the dev tools for a project that is hosted under a prefix URL.

**Comment by codehead** [comment]
Great work. Thank you!
