### ISSUE TITLE
fix: enabling timeline breaks makro imports

### ISSUE THREAD

**Issue by dargmuesli** [nuxt/devtools#507]
### 🐛 The bug

The `nuxt:pages-macros-transform` removes the whole line `
import { abortNavigation as _$__abortNavigation } from '#app';;import { __nuxtTimelineWrap } from "/home/projects/github-zpd6br/node_modules/@nuxt/devtools/dist/runtime/function-metrics-helpers";const abortNavigation = __nuxtTimelineWrap("abortNavigation", _$__abortNavigation);
`.

Letting `abortNavigation` be undefined.

### 🛠️ To reproduce

https://stackblitz.com/edit/github-zpd6br?file=pages%2Findex.vue

### 🌈 Expected behavior

`const abortNavigation = __nuxtTimelineWrap("abortNavigation", _$__abortNavigation);` is kept.

### ℹ️ Additional context

I think this error must be fixed in `nuxt`, not `devtools`. (cc @danielroe)

**Comment by daniluk4000** [comment]
Got weird errors with undefined composables in our project. Disabled timeline - and all of them got fixed.

**Comment by kylegl** [comment]
I ran into this in my project. Checked the repro above with the latest devtools and its erroring. This still seems to be an issue.

**Comment by dargmuesli** [comment]
> Checked the repro above with the latest devtools and its erroring

Could you share the link? :pray:

**Comment by kylegl** [comment]
> ### 🐛 The bug
> The `nuxt:pages-macros-transform` removes the whole line `import { abortNavigation as _$__abortNavigation } from '#app';;import { __nuxtTimelineWrap } from "/home/projects/github-zpd6br/node_modules/@nuxt/devtools/dist/runtime/function-metrics-helpers";const abortNavigation = __nuxtTimelineWrap("abortNavigation", _$__abortNavigation);`.
> 
> Letting `abortNavigation` be undefined.
> 
> ### 🛠️ To reproduce
> [stackblitz.com/edit/github-zpd6br?file=pages%2Findex.vue](https://stackblitz.com/edit/github-zpd6br?file=pages%2Findex.vue)
> 
> ### 🌈 Expected behavior
> `const abortNavigation = __nuxtTimelineWrap("abortNavigation", _$__abortNavigation);` is kept.
> 
> ### ℹ️ Additional context
> I think this error must be fixed in `nuxt`, not `devtools`. (cc @danielroe)

its the repro in the initial issue

**Comment by dargmuesli** [comment]
Yesyes, but my reproduction is from 2,5 months ago. You said that with a newer devtools version the issue reappeared, so it would be interesting to have a link to the updated reproduction you mentioned.

**Comment by kylegl** [comment]
Sorry for the confusion. Your repro package.json has `nuxt/devtools: latest` so it's currently using the latest version

**Comment by dargmuesli** [comment]
Oh, I didn't know that `latest` updates the lockfile on every install as it seems. I've update the original reproduction to have the devtools version my bug report was intended for (v1.0.1). With that version you had:
![image](https://github.com/nuxt/devtools/assets/4778485/07f25f5e-2871-4b0b-bd59-03c8b9f487be)

With devtools v1.0.8 you have:
![image](https://github.com/nuxt/devtools/assets/4778485/9f5336ed-cfba-4ab9-9944-5d01fcdb2a48)

as intended. Updated fork: https://stackblitz.com/edit/github-zpd6br-2ppzmo?file=package.json
