### ISSUE TITLE
PIP error in http

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/devtools#510]
### 🐛 The bug

PIP feature is throwing an error in `http` only

```
Uncaught (in promise) DOMException: Failed to execute 'requestWindow' on 'DocumentPictureInPicture': Opening a PiP window requires https or file protocol
```

I tried it and it did work on `https`

### 🛠️ To reproduce

n/a

### 🌈 Expected behavior

to work on `http`

**Comment by antfu** [comment]
Do you have a custom hostname? IIRC it works with localhost on http

**Comment by arashsheyda** [comment]
no nothing special, but It can be fixed simply by using [`https`](https://nuxt.com/docs/api/nuxt-config#https) option of nuxt

**Comment by antfu** [comment]
I guess there is nothing we could do on our side if it's a browser limitation. We could improve the UI to indicate better how to workaround this when it occurs. What do you think?

**Comment by arashsheyda** [comment]
Yes I totally agree

**Comment by tarushnagpal** [comment]
As a workaround you can develop on chrome 116 which was the first version which released pip for now, you can find it here (for mac) https://google-chrome.en.uptodown.com/mac/post-download/106936027
