### ISSUE TITLE
Unable to start recent version

### ISSUE THREAD

**Issue by ennioVisco** [nuxt/devtools#517]
### 🐛 The bug

Despite having latest version of nuxt and devtools, having purged the `pnpm` store, having deleted node_modules and lockfile, having used `npx nuxi@latest devtools enable`, and having the latest version in my `package.json` file, I still keep getting this:
![image](https://github.com/nuxt/devtools/assets/740025/b81fbe32-c965-4765-8f7c-19d6f8a078e0)

Any ideas how to fix it?

### 🛠️ To reproduce

-

### 🌈 Expected behavior

-

**Comment by antfu** [comment]
Please check `.nuxtrc` under your home dir, if there is one, you can trying removing it and restart the server again

**Comment by ennioVisco** [comment]
> Please check `.nuxtrc` under your home dir, if there is one, you can trying removing it and restart the server again

I seeeee. I read in the docs about a `.nuxtrc` but I understood it should have been in the project's root, not in the user home!

Thanks a lot!!
