### ISSUE TITLE
fix: Switching to a different color theme in an abnormal way.

### ISSUE THREAD

**Issue by setobox** [nuxt/devtools#525]
### 🐛 The bug

When I toggle `dark mode` using "@nuxtjs/color-mode", the Devtools switch to `dark mode` However, when I switch to another nav on the devtools panel, the Devtools's color theme switches back to `light mode`.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-xdwqux?file=app.vue

### 🌈 Expected behavior

I think the devtools shouldn't switch the color theme when I switch the side nav.

**Comment by arashsheyda** [comment]
fixed in #679
