### ISSUE TITLE
fix: font color error

### ISSUE THREAD

**Issue by maicss** [nuxt/devtools#527]
### 🐛 The bug

![image](https://github.com/nuxt/devtools/assets/9784767/ee133041-69ec-45e1-9c50-7dcdeb17ba78)

### 🛠️ To reproduce

-

### 🌈 Expected behavior

-

**Comment by antfu** [comment]
Can you explain a bit more?

**Comment by maicss** [comment]
What information do you need? Nuxt or devtool version?

**Comment by antfu** [comment]
What do you mean? If even you don't know how to reproduce, how could we help?

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by arashsheyda** [comment]
@maicss  are you using `nuxt-mongoose` DB playground? it looks like that

**Comment by maicss** [comment]
> @maicss  are you using `nuxt-mongoose` DB playground? it looks like that

Yes

**Comment by maicss** [comment]
![image](https://github.com/nuxt/devtools/assets/9784767/0d2fa30b-3a34-4b9d-98ad-0e59801cd6cf)
 Even when I change the theme of devtools form light to dark. Seems mongoose plugin does not change its theme with devtools. @arashsheyda

**Comment by arashsheyda** [comment]
@maicss you should open an issue on [`nuxt-mongoose`](https://github.com/arashsheyda/nuxt-mongoose) repository not here. thanks for noticing this
