### ISSUE TITLE
fix: 404 (Page not found: /@vite/client)

### ISSUE THREAD

**Issue by sergenux** [nuxt/devtools#528]
### 🐛 The bug

When Nuxt app has pages with "pages" folder and DevTools is open, refreshing the page gives an error in the console and a warning in the terminal.

![Error-1](https://github.com/nuxt/devtools/assets/147421571/0d7802f8-0c6d-4b2a-8fcf-a6c39478bd9f)
![Error-2](https://github.com/nuxt/devtools/assets/147421571/55d6878b-33a1-41ee-a15b-843d4b6ccf1b)

Also on stackblitz
![Error-3](https://github.com/nuxt/devtools/assets/147421571/ee908adb-6b69-4154-8b22-ad812ec65831)

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-9m9mym

### 🌈 Expected behavior

I think there should be no errors.

**Comment by sergenux** [comment]
Additionally:
Apps with ssr: false - no errors

**Comment by EmanueleDB** [comment]
I just updated the deps in one of my app and I have the same problem.

**Comment by christopherdbull** [comment]
Confirming over here too

**Comment by choliddnr** [comment]
any solution for this?

**Comment by veritimus** [comment]
This is really annoying.
