### ISSUE TITLE
Independent color mode for devtools

### ISSUE THREAD

**Issue by MuhammadM1998** [nuxt/devtools#543]
### 🐛 The bug

Not really a big issue, maybe a nitpick or nice to have.

Dark mode is generally preferred to work with, but sometimes we're working on a project that has light mode only as a requirement. Changing dev tools to dark mode via the toggle also changes the main app. Using a separate cookie for devtools might be nice and straightforward I think. I can take a try If this seems reasonable.

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-ui-ndmdji?file=app.vue,nuxt.config.ts

### 🌈 Expected behavior

Notice I'm forcing light mode by setting `colorMode.preference` to `light`.
Toggling the theme button in the app changes the app's and devtools theme.
Toggling the theme button in the devtools _and refresh_ changes the app's and devtools thene.
(Theme toggle button in the app is just for demonstration, realistically there won't be a toggle if we're enforcing 1 mode)

**Comment by antfu** [comment]
Make sense to have an option for this I think. PR welcome :)

**Comment by MuhammadM1998** [comment]
Cool! I'm on it

**Comment by arashsheyda** [comment]
resolved by #679
