### ISSUE TITLE
feat: Disabling twitter suggestion in OpenGraph-tab

### ISSUE THREAD

**Issue by Jak2k** [nuxt/devtools#551]
### 🆒 Your use case

When I go into the OpenGraph-tab, it tells me to add metadata for twitter. I'm not a twitter user and I don't want to support a platform, that is owned by a neo-nazi.

### 🆕 The solution you'd like

I would like to have a toggle in the settings to disable the suggestion for twitter-metadata.

### 🔍 Alternatives you've considered

Blocking it with my ad-blocker? (doesn't work well)

### ℹ️ Additional info

https://edition.cnn.com/2023/11/17/business/elon-musk-reveals-his-actual-truth/index.html

**Comment by antfu** [comment]
As Twitter does not display that info either, I think it makes sense to make them optional. Did it in 41ee5eca5e2cea5a1d093fb1a3bb4b9875adb819
