### ISSUE TITLE
Documentation is missing on the website.

### ISSUE THREAD

**Issue by joezimjs** [nuxt/devtools#555]
### 📚 Is your documentation request related to a problem?

The docs website is empty:

![image](https://github.com/nuxt/devtools/assets/1313898/9e173648-65f7-44c9-890e-7801bcf7a5e3)

The table of contents is showing there should be content on these pages, but there's nothing between the title area and the bottom navigation. This is happening on every page I looked at and I looked at quite a few.

Looking at the page source, it seems the content being passed to the MD renderer isn't getting passed correctly or everything is getting converted to strings when it shouldn't:

![image](https://github.com/nuxt/devtools/assets/1313898/4af4d61b-0fd5-402e-b6ff-3a74b43a452f)

### 🔍 Where should you find it?

All the pages should have their content.

### ℹ️ Additional context

I doubt it matters but I'm using Windows 10 and I tried a couple Chromium-based browsers.

**Comment by IonianPlayboy** [comment]
For what it's worth, I'm seeing the same on a Macbook with Firefox and Chrome. Disabling the cache and reloading the pages does not fix the issue either.

**Comment by arashsheyda** [comment]
It should be fixed now, can you confirm?

**Comment by antfu** [comment]
Should be fixed. Thanks for reporting.
