### ISSUE TITLE
help: Can't connect to the server, maybe a Websock issue—only on my computer

### ISSUE THREAD

**Issue by ahku** [nuxt/devtools#557]
### 📚 What are you trying to do?

A while ago my devtools just stopped working. I thought it was a temporary bug, but later I learnt that it still worked for my colleagues and even after several versions later it still has not worked for me. Since it's the same in all browsers (On Mac: Chrome, Safari, Firefox and Edge) I've concluded that it must be a system setting error of some sort. Maybe my firewall is blocking something, but I don't have any issues with any other websocket applications that I know of.

So now I'm pretty desperate to get this working again as a new work year starts. 

Can anybody help me sort this ut?

![The issue](https://github.com/nuxt/devtools/assets/1736890/88a5928f-0d99-4cef-9e96-ab443fa6753a)

![Console error](https://github.com/nuxt/devtools/assets/1736890/8dc48314-c500-4ac0-9131-60174d8e34b0)

### 🔍 What have you tried?

I've gone through the docs, created a new starter project from scratch, tested it in all of my Nuxt projects, in different browsers and so on. I would have provided a reproduction repo if I didn't know for sure that it was a me problem: It used to work, and now it doesn't, but it's only on my computer.

### ℹ️ Additional context

I'm using a M1 Mac, and I'm still on Ventura 13.4.1. Might upgrade soon.

**Comment by ahku** [comment]
Update: The new Vue dev tools (vite-plugin-vue-devtools) work for me, so. not sure what Nuxt devtools are doing differently?

**Comment by arashsheyda** [comment]
you are probebly using an old cached version of devtools
have you tried this? https://github.com/nuxt/devtools/issues/517#issuecomment-1814545568

**Comment by ahku** [comment]
> you are probebly using an old cached version of devtools have you tried this? [#517 (comment)](https://github.com/nuxt/devtools/issues/517#issuecomment-1814545568)

Thanks, that really solved the issue! Perhaps this should be mentioned in the docs? I saw in the replies that someone read about it there but I could not find it myself.
