### ISSUE TITLE
`@apply` in ui-kit conflicts with Tailwind

### ISSUE THREAD

**Issue by alvarosabu** [nuxt/devtools#565]
### 🐛 The bug

Hi there, I'm trying to add a `NSplitPane` to Tres Devtools form `@nuxt/devtools-ui-kit` and I get this error:

```bash
[vite-node] [plugin:vite:css] [CssSyntaxError] ./node_modules/@nuxt/devtools-ui-kit/dist/components/NSplitPane.vue:65:2 : The `border-base` class does not exist. If `border-base` is a custom class, make sure it is defined within a `@layer` directive.

19 |    min-width: 0 !important;
20 |    width: 0 !important;
21 |    @apply border-r border-base;
   |    ^
22 |  }
23 |  .splitpanes--horizontal > .splitpanes__splitter {
```

If I remove the `@nuxt/ui` module it works. Maybe the unocss configs are colliding?

### 🛠️ To reproduce

https://stackblitz.com/edit/nuxt-starter-xhtgcu?file=nuxt.config.ts

### 🌈 Expected behavior

Being able to use NSplitPane

**Comment by antfu** [comment]
Yeah I think it conflicts with Tailwind. I'll see what we could do
