### ISSUE TITLE
Avoid `nitropack` (type) dependency for `@nuxt/devtools`

### ISSUE THREAD

**Issue by pi0** [nuxt/devtools#571]
Hi. Opening this issue as spotted random peer dependency issues a couple of times originating from the `nitropack` dependency in `@nuxt/devtools` in the dependency tree.

Having extra dependencies of core packages such as `vite` or `nitropack` often can contribute to more package manager hoisting issues and unpredictable warns.

Quickly [searching across repo](https://github.com/search?q=repo%3Anuxt%2Fdevtools%20nitropack&type=code) it seems it is only used as a type dependency. In similar situations (like `@nuxt/schema`) we add them to `build.externals` (seems you also already did!) and simply keep nitropack as a `devDependency`

**Comment by arashsheyda** [comment]
I think that applies for `h3` and `ofetch` too?
