### ISSUE TITLE
help: Cannot disable devtools

### ISSUE THREAD

**Issue by Allypost** [nuxt/devtools#587]
### 📚 What are you trying to do?

I tried enabling devtools and had some issues.
Trying to debug things, I tried disabling devtools unsuccessfully.
Whatever I do, the dev server gives me `  ➜ DevTools: press Shift + Alt + D in the browser (v1.0.8)`

### 🔍 What have you tried?

1. `yarn nuxi devtools disable`:
```
 Nuxt 
 DevTools  v1.0.8

Learn more at https://devtools.nuxt.com

Disabling Nuxt DevTools...
ℹ Nuxt DevTools is already disabled
✔ Nuxt DevTools disabled for this project.
```
2. `yarn remove @nuxt/devtools`:
```
Usage Error: Pattern @nuxt/devtools doesn't match any packages referenced by any workspace

$ yarn remove [-A,--all] [--mode #0] ...
```
3. `rm -rf node_modules/ .nuxt/ .nuxtrc ~/.nuxtrc ~/.config/.nuxtrc` for good measure
4. `yarn` to re-install deps
5. `yarn nuxi dev` just to have the devtools message appear

I don't have devtools enabled in my `nuxt.config.ts` either

**Comment by antfu** [comment]
DevTools in enabled by default in since Nuxt 3.8. To disable it, you add `{ devtools: { enabled: false }}` to your config - the command is no longer used.

**Comment by platform-kit** [comment]
@antfu where was that announced? The docs seem to still recommend the command:

https://devtools.nuxt.com/guide/getting-started#install-using-nuxi
