### ISSUE TITLE
feat: integration with pinia 

### ISSUE THREAD

**Issue by Barbapapazes** [nuxt/devtools#592]
### 🆒 Your use case

Hello,

I'm using pinia and being able to visualize state and getters could help (like any other data in the devtools).

### 🆕 The solution you'd like

Something like https://devtools-next.vuejs.org/guide/features#pinia

**Comment by antfu** [comment]
This is definitely in the plan. We are working with @webfansplz to resuse some modules from Vue DevTools to Nuxt DevTools
