### ISSUE TITLE
help: Unable to Use Nuxt DevTools When Enabling Cross-Origin Isolation for Web Containers

### ISSUE THREAD

**Issue by Speelwolf** [nuxt/devtools#595]
### 📚 What are you trying to do?

I'm trying to configure COOP/COEP headers in my Nuxt application to enable working with web containers. Specifically, I need to set the following headers:

- Cross-Origin-Embedder-Policy: require-corp
- Cross-Origin-Opener-Policy: same-origin

### 🔍 What have you tried?

- I tried setting the headers in server/middleware/web-container-headers.ts :

![SettingHeaders](https://github.com/nuxt/devtools/assets/92581654/3d633205-07b5-4012-9fa0-df2ffd6d8f07)

- I also tried using Nuxt Security

### ℹ️ Additional context

I'm unable to use Nuxt devtools. Specifically, I encountered the following error in the console:

![DevtoolsError](https://github.com/nuxt/devtools/assets/92581654/e5daacb6-e979-4653-99eb-8218f9a64095)

**Comment by tillsanders** [comment]
I'm not sure, but are these links any help? I had a somewhat similar issue and they solved mine:

- https://nuxt-security.vercel.app/documentation/getting-started/setup#using-with-nuxt-devtools
- https://github.com/Baroshem/nuxt-security/issues/101#issuecomment-1434588875

**Comment by Speelwolf** [comment]
The COOP/COEP headers are needed even in development because WebContainer requires SharedArrayBuffer.

**Comment by nandordudas** [comment]
> [!NOTE]
> Here are the changes I made to get `Devtools` working with header routes - hopefully this helps others facing the same problem.
> Nuxt security module is not required but recommended.

```ts
// .config/nuxt.ts
export default defineNuxtConfig({
  // ...
  experimental: {
    inlineRouteRules: true,
  },
  modules: ['nuxt-security'],
  hooks: {
    'vite:serverCreated': (server) => {
      server.middlewares.use((_req, res, next) => {
        res.setHeader('Cross-Origin-Resource-Policy', 'same-origin')
        res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp')
        res.setHeader('Cross-Origin-Opener-Policy', 'same-origin')
        res.setHeader('Access-Control-Allow-Origin', 'https://localhost:3000')
        next()
      })
    },
  },
})
```

```html
<!-- pages/acme.vue -->
<script setup lang="ts">
defineRouteRules({
  security: {
    headers: {
      crossOriginEmbedderPolicy: 'require-corp',
      crossOriginOpenerPolicy: 'same-origin',
    },
  },
})
</script>
```

Because of the secure origin.

```ini
# ~/.nuxtrc
devServer.https.key=".../localhost+3-key.pem"
devServer.https.cert=".../localhost+3.pem"
```

```ts
console.log(globalThis.crossOriginIsolated, 'SharedArrayBuffer' in globalThis) // true true
```

Have a nice day, bye

**Comment by Hebilicious** [comment]
In case anyone stumble onto this, here's a working solution that doesn't involve nuxt-security.

```ts
export default defineNuxtConfig({
  compatibilityDate: "2024-11-01",
  future: {
    compatibilityVersion: 4
  },
  routeRules: {
    "/": {
      headers: {
        "Cross-Origin-Opener-Policy": "same-origin",
        "Cross-Origin-Embedder-Policy": "require-corp"
      }
    }
  },
  hooks: {
    "vite:serverCreated": (server) => {
      server.middlewares.use((_req, res, next) => {
        res.setHeader("Cross-Origin-Embedder-Policy", "require-corp")
        res.setHeader("Cross-Origin-Opener-Policy", "same-origin")
        next()
      })
    }
  },
  devtools: { enabled: true }
})
```
