### ISSUE TITLE
feat: detect unused components to help clean up old code

### ISSUE THREAD

**Issue by acidjazz** [nuxt/devtools#597]
### 🆒 Your use case

Have a CTA or auto-run something that shows all found components that are not used

### 🆕 The solution you'd like

A list of all components not found to be used

### ℹ️ Additional info

Be very cool to make sure stale code can be removed from the project

**Comment by acidjazz** [comment]
I understand `<component :is`  might make this tricky, maybe list where those are as well as a warning

**Comment by manniL** [comment]
Closing in favor of #358
