### ISSUE TITLE
feat: add option to hide `devtools` panel on smaller screen sizes

### ISSUE THREAD

**Issue by stefanobartoletti** [nuxt/devtools#599]
### 🆒 Your use case

I find the small `devtools` indicator that permanently resides at the bottom of the screen to be a little intrusive when working on responsive layouts, i.e. when using a browser "device view" to see smaller screens. 

On mobile screens, often UI elements are smaller and more difficult to interact with (to test or inspect them)  when the `devtools` indicator is present and gets in the way.

![Screenshot_20240216_133640](https://github.com/nuxt/devtools/assets/36746429/fbd639be-4b5c-477e-ae11-135e92e8ab45)

And I would also say that `devtools` window is not really that useful in these resolutions since the screen is too small to provide information in a viable way.

![Screenshot_20240216_133714](https://github.com/nuxt/devtools/assets/36746429/0cbdc9c3-06a8-4763-ba3a-0ae193755810)

### 🆕 The solution you'd like

Give the ability to completely hide `devtools` when the site is displayed on smaller resolutions (probably the simplest way would be to just hide it from CSS). Maybe this could be optional so the user can choose whether it has to be hidden or not, and maybe use three generic "mobile", "tablet" and "desktop" breakpoints for fine-tuning.

**Comment by stefanobartoletti** [comment]
Thanks for your feedback!

I found that on my Linux system the shortcut to activate/deactivate it is `Shift` + `Alt` + `D`.

Besides that, this behavior is slightly different to what I'd like to have, I'm fine with having the indicator always present on desktop and only hiding it on mobile views. I think that for the time being I can resort on using a custom Userscript on my browser.

**Comment by arashsheyda** [comment]
I'm not sure if this is something we want? /cc @antfu

@stefanobartoletti meanwhile you can do something like this:

```css
@media screen and (max-width: 768px) {
  .nuxt-devtools-panel,
  .nuxt-devtools-glowing {
    display: none !important;
  }
}
```

**Comment by antfu** [comment]
I heard there are some people using DevTools on mobile devices to debug, as one of the advantage of Nuxt DevTools is that it also works on mobile where native DevTools is hard to setup. While I agree to hide it on smaller screens, but I would like to keep the possibilities for people to use Nuxt DevTools if they want to

**Comment by stefanobartoletti** [comment]
@antfu yes, this is a bit old as issue, right now I'm using it hidden by default and pop it up with `Shift`+`Alt`+`D` when needed, and it works nice for my workflow. So in a sense we can consider this solved.
