### ISSUE TITLE
[unhandledRejection] Cannot read properties of undefined (reading 'content') 

### ISSUE THREAD

**Issue by stephenjason89** [nuxt/devtools#60]
This error occurs when you click Overview for the first time
<img width="719" alt="image" src="https://user-images.githubusercontent.com/3810177/218639642-c9194848-fb96-4714-8f2f-5118eee73c36.png">

**Comment by Lmmmmmm-bb** [comment]
duplicate of https://github.com/nuxt/devtools/issues/41

**Comment by manniL** [comment]
Let's track in https://github.com/nuxt/devtools/issues/41
