### ISSUE TITLE
docs: listed `pnpm` version in docs is different than `package.json`

### ISSUE THREAD

**Issue by nmggithub** [nuxt/devtools#605]
### 📚 Is your documentation request related to a problem?

The Contribution Guide says "[Nux DevTools uses pnpm v7](https://github.com/nuxt/devtools/blob/15b7fb4/docs/content/3.development/0.contributing.md?plain=1#L20)", but the `package.json` lists [v8.14.1](https://github.com/nuxt/devtools/blob/e755e35/package.json#L6). Is there a reason for this discrepancy?

**Comment by arashsheyda** [comment]
@nmggithub no it just got updated alongside other dependencies during time...

**Comment by nmggithub** [comment]
@arashsheyda Ok, so is any change needed for this?

**Comment by arashsheyda** [comment]
@nmggithub if you would like you can update it in docs and open a PR? thanks

**Comment by averrois** [comment]
I will do it
