### ISSUE TITLE
fix: devtools stuck on Welcome page on mobile screen; 'Get Started' button cannot be clicked

### ISSUE THREAD

**Issue by yllaw** [nuxt/devtools#615]
### 🐛 The bug

I am using a physical iPhone 12 device and I cannot get past the welcome screen due to the button being hidden under the checkbox 'Send anonymous statistics...'

https://github.com/nuxt/devtools/assets/16358778/aca8a5f2-6634-4f80-a137-b50bb9ac28d8

### 🛠️ To reproduce

n/a

### 🌈 Expected behavior

The 'Get Started' button should be stacked above/below the checkbox so it can be tappable/clickable to continue to the DevTools.

**Comment by arashsheyda** [comment]
@yllaw you can resize the DevTools window:

https://github.com/nuxt/devtools/assets/38922203/a6f12191-0c6c-48bc-9ae6-2f5ad84b294e

**Comment by yllaw** [comment]
> @yllaw you can resize the DevTools window:
> 

Hi thanks for the reply,

Unfortunately it does not work for me. I am building with Capacitor so it's effectively a mobile app and perhaps the touch events don't allow for the window resize. Here is a video of me attempting to resize the window via pinching action on a physical touch screen:


https://github.com/nuxt/devtools/assets/16358778/9388c861-46c2-4b69-b575-57c3eeecee5c


Currently I am using [standalone Vue devtools](https://devtools.vuejs.org/guide/installation.html#standalone) as a workaround and that works well.

**Comment by arashsheyda** [comment]
@yllaw Oh I see, thanks for the info. I'll try to find a fix!

**Comment by darylteo** [comment]
I *was* able to do this on a capacitor build. Seems to work only on the top right corner only.
