### ISSUE TITLE
Windows: project path incorrect in nuxtrc

### ISSUE THREAD

**Issue by cailliaud** [nuxt/devtools#62]
# Windows: project path wrong syntaxe

## env:
I am on Windows OS.
The devtools is not activated on my project even after running the command to enable it.

## Minimal reproduction:
- run command `npx nuxi@latest devtools enable` in a nuxt project on Windows
- Launch project
- Go on website page
- There is no Nuxt Bubble on the page and the ALT + D command does not work 

## Origin of the troubleshooting
THe path written in the `~.nuxtrc` is invalid for Windows 

This is an example of the configuration file initiated by the command line
```
telemetry.enabled=false
modules.0=E:/npm/node_modules/@nuxt/devtools/module.cjs
devtoolsGlobal.projects.0=E:\PROJECT\MyProject
```

## How to fix it:
I had to rework the path to my project in `~.nuxtrc`
Just replacing backslash `\` by slash `/` was enought

```
telemetry.enabled=false
modules.0=E:/npm/node_modules/@nuxt/devtools/module.cjs
devtoolsGlobal.projects.0=E:/PROJECT/MyProject
```

**Comment by Barbapapazes** [comment]
I've still the issue in 0.1.6

**Comment by Rednas83** [comment]
I am not even able to run the enable command
![image](https://user-images.githubusercontent.com/25219229/222679157-dbf64b2f-3ffd-4eea-a8e6-002f92c00720.png)
