### ISSUE TITLE
Uncaught Error: Module "node:perf_hooks" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by manniL** [nuxt/devtools#64]
Follow-up of #61, most likely due to https://github.com/nuxt/devtools/commit/c7f83f84924c48ffcdc49aa389c5de20ab894088

When starting current main branch locally, you receive the following error message. Reverting https://github.com/nuxt/devtools/commit/c7f83f84924c48ffcdc49aa389c5de20ab894088 fixes the issue.

> Uncaught Error: Module "node:perf_hooks" has been externalized for browser compatibility. Cannot access "node:perf_hooks.performance" in client code.  See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

**Comment by Lmmmmmm-bb** [comment]
Same issue when starting main branch.
