### ISSUE TITLE
feat: theme configuration

### ISSUE THREAD

**Issue by arashsheyda** [nuxt/devtools#653]
### 🆒 Your use case

for example some custom tabs are using nuxt UI, and their theme doesn't match with DevTools UI

### 🆕 The solution you'd like

add theme configuration into settings tab so user can change DevTools colours

**Comment by antfu** [comment]
I don't think this is possible - basically, every tab is in charge of their own UI via iframes, where everything is isolated, we couldn't interfere anything inside them.
