### ISSUE TITLE
fix: Devtools "Open Graph" tab layout

### ISSUE THREAD

**Issue by hmd-ali** [nuxt/devtools#665]
### 🐛 The bug

Open Graph tabs has 2 parts,  let's call them Details and Preview
on smaller widths,  they are on top of each others, which is fine. however when u resize the devtools to be more than 1024px wide, The Preview part takes the whole screen (h-full) because the container is not applying the `lg:row` class. 

### 🛠️ To reproduce

none

### 🌈 Expected behavior

when resizing the devtools above 1024px,  the tabs mentioned above should be both visible and on top of each other.

### ℹ️ Additional context

- ![image](https://github.com/nuxt/devtools/assets/83613364/4bb70161-fdd8-4e96-b081-b9712e3f579f)
- ![image](https://github.com/nuxt/devtools/assets/83613364/7bc326e2-fef7-477d-a036-b80f5a3f4c3e)
- suspect line of code responsible https://github.com/nuxt/devtools/blob/33fe6857dabff26a0cb30fb1b1f170e8a658a96b/packages/devtools/client/pages/modules/open-graph.vue#L96 (I have no idea what css tool is this)

**Comment by arashsheyda** [comment]
@hmd-ali we're using [UnoCSS](https://unocss.dev/), PR welcome if you want to work on this
