### ISSUE TITLE
fix: Component Cloud Search Bar Gone?

### ISSUE THREAD

**Issue by GrantlyNeely** [nuxt/devtools#693]
### 🐛 The bug

I am trying to use the component cloud and the "search bar" is not appearing. It seem that the documentation indicates that this should be present. I apologize if this is a simple setting. I have searched everywhere and cannot find it.

<img width="1422" alt="Screenshot 2024-07-11 at 11 19 46 AM" src="https://github.com/nuxt/devtools/assets/102992367/6631b4a8-05e0-47b6-b624-1397f5e3091f">

### 🛠️ To reproduce

n/a

### 🌈 Expected behavior

I would expect the search bar to appear.

**Comment by arashsheyda** [comment]
we don't have search functionality in graph mode.

@antfu do you think it's worth adding it?

**Comment by antfu** [comment]
We could - but I am not share how we could present the graph - if the dots are disconnceted. Maybe using highlights? Instead of filtering the nodes, we highlight the nodes that match the search?

**Comment by arashsheyda** [comment]
I agree!
