### ISSUE TITLE
fix: DevTools cannot be showed in Chrome and Firefox on Nuxt v4

### ISSUE THREAD

**Issue by pan93412** [nuxt/devtools#698]
### 🐛 The bug

I am using the nightly version of Nuxt ([4.0.0-28693174.8aefb554](https://www.npmjs.com/package/nuxt-nightly/v/4.0.0-28693174.8aefb554)). I found Nuxt DevTools (no matter the nightly or `@nuxt/devtools@1.3.9`) does not work on Chrome 126 and Firefox 129.0b6 (Attachment 2). Notably, it works on Safari 17.5 (Attachment 1). It used to work on Nuxt v3.

![image](https://github.com/user-attachments/assets/50bfe860-5b9f-4915-bfa1-d132fb76165d)
![image](https://github.com/user-attachments/assets/c5209035-3f35-4d34-a834-50087e89df92)

When adding breakpoints to the code related to Nuxt DevTools, I found Firefox (and Chrome) indeed ran `import("./view/client")` but `setupDevToolsClient` was never called, as the Attachment 3 shown. Safari ran as expected (Attachment 4). Not sure why.

https://github.com/user-attachments/assets/df0c3b68-3e77-4791-ba55-f837bfe0efb5

https://github.com/user-attachments/assets/0ad4a9cd-7570-4cb4-b62f-df250b996a32

### 🛠️ To reproduce

https://github.com/pan93412/nuxt-4-devtools-regression

### 🌈 Expected behavior

The Nuxt DevTools should be able to show on Chrome, Firefox, and Safari.

### ℹ️ Additional context

I am using macOS 14.5 (23F79) if this matters.

**Comment by pan93412** [comment]
Upgraded to the latest nightly ([4.0.0-28693174.8aefb554](https://www.npmjs.com/package/nuxt-nightly/v/4.0.0-28693174.8aefb554) and this is still reproducible.

https://github.com/user-attachments/assets/0f9c20a6-367a-48dd-a2ba-a0953dc1a797

![telegram-cloud-photo-size-5-6125390261027717374-y](https://github.com/user-attachments/assets/c0fafb38-3234-489e-8e5f-509320c1cd6b)

**Comment by pan93412** [comment]
After the bisecting of Nuxt version, I found this issue is started from the Nuxt commit `8f95cac3`: <https://github.com/nuxt/nuxt/compare/5f819ab8..8f95cac3>. In another word, it works in the previous Nightly version, `5f819ab8`.

Sadly, the `8f95cac3` commit is about the upgradation of [Nitro](https://nitro.unjs.io/). Maybe I need to deep into what makes DevTools break.

**Comment by pan93412** [comment]
After the final investigation, I can conclude this bug is a due to the circular import.

`#app/config` contains this import:

```ts
import { reactive } from 'vue'
import { klona } from 'klona'
import type { AppConfig } from 'nuxt/schema'
import { useNuxtApp } from './nuxt'
// @ts-expect-error virtual file
import __appConfig from '#build/app.config.mjs'  // oops
```

`#build/app.config.mjs` is basically the content I mentioned above:

```js
import { defuFn } from 'defu'

const inlineConfig = ${JSON.stringify(nuxt.options.appConfig, null, 2)}

/** client **/
// Vite - webpack is handled directly in #app/config
if (import.meta.dev && !import.meta.nitro && import.meta.hot) {
  const { updateAppConfig } = await import('#app/config')  // oops
  import.meta.hot.accept((newModule) => {
    updateAppConfig(newModule.default)
  })
}
/** client-end **/
```

@danielroe Would you like to take a look with this issue? I can open a PR to revert the `await import('#app/config')` to `import { updateAppConfig } from '#app/config'`.

**Comment by danielroe** [comment]
Thank you @pan93412 - that would be very helpful 🙏
