### ISSUE TITLE
The Nuxt panel opens empty in the Chrome Dev browser

### ISSUE THREAD

**Issue by beierzhijin** [nuxt/devtools#708]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.16.0
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  pnpm@9.7.1
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

just start a new nuxt project use `pnpm dlx nuxi@latest init nuxt-test`

### Describe the bug

The Nuxt panel opens as blank in the `Chrome Dev Edition 129.xxx`,
![image](https://github.com/user-attachments/assets/336fbbb3-f31a-423d-bb72-af9fcb5e93ed)
![image](https://github.com/user-attachments/assets/e9a754a9-d79b-42b1-bc27-ca3f1748ab15)

But it works in `Edge browser` and `Chrome official version`.

![image](https://github.com/user-attachments/assets/4ccf70a3-8292-412b-9647-1ddf9501708b)

**Comment by antfu** [comment]
Which sounds like a Chrome bug? I don't think we would have the bandwidth to provide support for unstable browser engines. I'd suggest just waiting for the stable releases, or you can report to the browser side. Thanks.

**Comment by robert-hoffmann** [comment]
This bug is now in the latest official version of chrome

https://github.com/nuxt/devtools/issues/723

**Comment by sosensible** [comment]
I am seeing the issue in both Edge and Arc, which are both Chrome based.

**Comment by robert-hoffmann** [comment]
> I am seeing the issue in both Edge and Arc, which are both Chrome based.

fix is underway
https://github.com/nuxt/devtools/issues/723
