### ISSUE TITLE
Feature Request: Support custom shortcut keys

### ISSUE THREAD

**Issue by alexzhang1030** [nuxt/devtools#72]

**Comment by okxiaoliang4** [comment]
Agree, and I also want a command panel. I am trying

**Comment by Atinux** [comment]
What is wrong with `Alt+D` ?

**Comment by ennioVisco** [comment]
> What is wrong with `Alt+D` ?

That it's used on Windows by Chrome to select the address bar. See: https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Caddress-bar-shortcuts:~:text=Ctrl%20%2B%20l%20or-,Alt%20%2B%20d,-or%20F6

**Comment by ennioVisco** [comment]
> What would you use instead @ennioVisco ?

On windows and Linux I think F12 is used to open the developer tools. What about CTRL+F12?

**Comment by ManUtopiK** [comment]
I confirm it's very annoying with Linux. 
What about CTRL+ALT+D ? Tested with Firefox, Google chrome, Chromium and Vivaldi. It's free...
