### ISSUE TITLE
fix: extendServerRpc does not register function

### ISSUE THREAD

**Issue by rrd108** [nuxt/devtools#725]
### 🐛 The bug

When I use the example code for the docs to register a server rpc function it seems to be ignored.

If you start the project it will log a few messages to the console.

One of them will be `RPC object: { broadcast: {} }` and it is created by `module.ts` line 40.

### 🛠️ To reproduce

https://stackblitz.com/~/github.com/rrd108/vue-mess-detector-nuxt-devtools

### 🌈 Expected behavior

The `rpc` object should have a `getResults` function registered.

### ℹ️ Additional context

The code here is almost the same what is in the docs. If I use the doc's code, I get the same result.

**Comment by arashsheyda** [comment]
@rrd108 you have to use `extendClientRpc`, would you like me to open a PR on your repo or post the example solution here?
