### ISSUE TITLE
Feature Request: Command panel

### ISSUE THREAD

**Issue by okxiaoliang4** [nuxt/devtools#73]
Quickly jump to a tab or run a feature.

**Comment by Atinux** [comment]
Is it not good enough to click on the tab on the left right now?

**Comment by Atinux** [comment]
It might be tricky if you project also have a command palette 🤔

**Comment by arashsheyda** [comment]
@Atinux can the priority be the clicked window? I mean if user click on devtools window and press `ctrl + k` for example, it would open the devtools command panel

<details>
  <summary>example video</summary>
  

https://github.com/nuxt/devtools/assets/38922203/2108e973-b0ad-438e-8d19-bb10371fa74e


  ```
</details>

**Comment by antfu** [comment]
Have a command panel in the DevTools view sounds good to me! Go ahead to send a PR @arashsheyda if you are already working on it!

**Comment by arashsheyda** [comment]
@antfu sure!

**Comment by Atinux** [comment]
Awesome!

**Comment by antfu** [comment]
Closing this for now as the main feature is implemented. For future feature enhancements, we could create other issues.
