### ISSUE TITLE
fix: The Nuxt panel opens empty in both Chrome and Edge browsers

### ISSUE THREAD

**Issue by HarleyQiu** [nuxt/devtools#732]
#### Versions:
- **Edge version**: 129.0.2792.52 (Official Build) (64-bit)
- **Chrome version**: 129.0.6668.59 (Official Build) (64-bit)
- **Nuxt**: ^3.13.0
- **@nuxt/devtools**: latest

#### Steps to Reproduce:
1. Install Nuxt and @nuxt/devtools.
2. Open Chrome or Edge browser.
3. Open Nuxt DevTools panel.
![image](https://github.com/user-attachments/assets/5a0c2f01-dc86-4ebc-8350-ffe506397f9b)

### 🛠️ To reproduce

none

### 🌈 Expected behavior

The Nuxt DevTools panel should display the expected devtools interface.

### ℹ️ Additional context

The Nuxt DevTools panel opens but is completely empty in both Chrome and Edge.

**Comment by manniL** [comment]
See https://github.com/nuxt/devtools/issues/723
