### ISSUE TITLE
docs: existing links to "VS Code Server" should be updated

### ISSUE THREAD

**Issue by NdagiStanley** [nuxt/devtools#750]
### 📚 Is your documentation request related to a problem?

The following are the concerned links:

- <https://github.com/nuxt/devtools/blob/a6e0bdcd09d3fd5b87b5c1ff895964c44d3eb686/docs/content/1.guide/1.features.md?plain=1#L95>
- <https://github.com/nuxt/devtools/blob/a6e0bdcd09d3fd5b87b5c1ff895964c44d3eb686/packages/devtools/src/integrations/vscode.ts#L151>

The existing links point to an outdated post on the "Visual Studio Code" blog [here](https://code.visualstudio.com/blogs/2022/07/07/vscode-server). While there's an updated blog post mentioned in said outdated post; find it [here](https://code.visualstudio.com/blogs/2022/12/07/remote-even-better), it's likely that more posts have followed or may could follow.

I suggest linking to the "VS Code Server" documentation page [here](https://code.visualstudio.com/docs/remote/vscode-server), instead.

### 🔍 Where should you find it?

Just where it is. I'm not suggesting that the docs' copy or location should change. Only the link should be updated.

![Image](https://github.com/user-attachments/assets/2aa3dfcf-dc5d-4d5b-9289-551ad5ed3802)

![Image](https://github.com/user-attachments/assets/c3c2cea1-f8c7-43fc-b951-4af4c4181f6b)

**Comment by antfu** [comment]
I am aware of their newer version of the code server; however, the last time I checked it, because they are moving to the tunnel approach instead of self-host locally, it wouldn't work on Nuxt DevTools because of CORS limits. I am not sure if there would be a solution for that at this moment, so for now, we need to point to the old post for users to follow the legacy approach. If they eventually deprecate that while we can't find a good solution to workaround, we might unfortunately need to remove this feature from Nuxt DevTools.

**Comment by NdagiStanley** [comment]
Thank you for the response, @antfu!
That's a great argument.

Please note that, the linked blog post claims that "VS Code Server is in private preview" and points a Nuxt user to sign-up:

![Image](https://github.com/user-attachments/assets/aec19255-96cd-4cc8-85f4-2619a01a95da)

yet the form is closed and points to the non-legacy approach: https://aka.ms/vscode-server-doc
![Image](https://github.com/user-attachments/assets/9b514ac7-1430-4052-b549-c7cc73d817b0)

Therefore, the Nuxt user is eventually sent to the newer approach. I agree with you that if they eventually deprecate and you can't find a good solution to workaround, then you might need to remove this feature from Nuxt DevTools.

In the meantime, maybe having the legacy approach (captured in the linked blog post) documented in Nuxt documentation may suffice. What do you think? I'm happy to help with that effort.

**Comment by NdagiStanley** [comment]
Seen that this PR was closed by #763 
Cheers.
