### ISSUE TITLE
docs: How to configure the port of eslint config inspector ?

### ISSUE THREAD

**Issue by BaptisteCrouzet** [nuxt/devtools#762]
### 📚 Is your documentation request related to a problem?

Hi,

I am looking for how to specify a port for eslint config inspector, launched through the Nuxt devtools.
As I am working on Windows with the WSL, I made my own image and opened some ports (3000 for dev server, 6006 for storybook) and the devtools are opening the port 8123 for the eslint config inspector :

>  node /usr/src/app/node_modules/.pnpm/@eslint+config-inspector@0.5.6_eslint@9.16.0_jiti@2.4.1_/node_modules/@eslint/config-inspector/bin.mjs --no-open
> 
> ℹ Starting ESLint config inspector at http://localhost:8123 

How to make this port always the same in order to open it on my image ? Is there any options to configure in the nuxt.config.ts file ?

### 🔍 Where should you find it?

In the "features" page https://devtools.nuxt.com/guide/features

### ℹ️ Additional context

Working in WSL, fixed ports are needed
I saw also that the eslint config inspector package mentions the 7777 port

**Comment by antfu** [comment]
That view is contributed by https://github.com/nuxt/eslint, I just released 0.7.4 exposing the option for you to config: https://github.com/nuxt/eslint/releases/tag/v0.7.4

**Comment by BaptisteCrouzet** [comment]
Perfect, thank you !
