### ISSUE TITLE
Vite peer dependencies warning

### ISSUE THREAD

**Issue by kingyue737** [nuxt/devtools#765]
### 🐛 The bug

Install a Nuxt 3.15.0 project via pnpm:
```
 WARN  Issues with peer dependencies found
.
└─┬ nuxt 3.15.0
  └─┬ @nuxt/devtools 1.6.4
    └─┬ vite-plugin-vue-inspector 5.1.3
      └── ✕ unmet peer vite@"^3.0.0-0 || ^4.0.0-0 || ^5.0.0-0": found 6.0.5 in @nuxt/vite-builder
```

### 🛠️ To reproduce

https://stackblitz.com/edit/github-9r73vjmb

### 🌈 Expected behavior

No warning

### ℹ️ Additional context

`vite-plugin-vue-inspector` v5.3 has supported vite v6 while `@nuxt/devtools` pins it to v5.1.3

**Comment by antfu** [comment]
Should be fixed in v1.7.0
