### ISSUE TITLE
Error while requiring module C:/Program Files/nodejs/node_modules/@nuxt/devtools: Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt/devtools#79]
ERROR  Cannot start nuxt:  EISDIR: illegal operation on a directory, read                                                   21:11:19  

  at Object.readSync (node:fs:748:3)
  at tryReadSync (node:fs:448:20)
  at readFileSync (node:fs:494:19)
  at jiti (node_modules\jiti\dist\jiti.js:1:249418)
  at requireModule (/D:/Programming/got/node_modules/@nuxt/kit/dist/index.mjs:286:26)
  at normalizeModule (/D:/Programming/got/node_modules/@nuxt/kit/dist/index.mjs:454:55)
  at installModule (/D:/Programming/got/node_modules/@nuxt/kit/dist/index.mjs:434:47)
  at initNuxt (/D:/Programming/got/node_modules/nuxt/dist/index.mjs:2162:13)
  at async load (/D:/Programming/got/node_modules/nuxi/dist/chunks/dev.mjs:6798:9)
  at async Object.invoke (/D:/Programming/got/node_modules/nuxi/dist/chunks/dev.mjs:6859:5)

Complete log - https://goonlinetools.com/snapshot/code/#wvt19nma0qnsi0vouyfl9

**Comment by toniengelhardt** [comment]
I keep getting it even after disabling `devtools`, dev server doesn't start anymore...

**Comment by rahulkumarsingh73690** [comment]
@toniengelhardt I removed node modules multiple times and fresh install but the same issue.

**Comment by LynxTR** [comment]
I am seeing this issue on my ubuntu 22.10 machine.

**Comment by tdwells90** [comment]
The easiest way to get back up and running is to go to your home directory (`cd ~`) and delete the `.nuxtrc` file with `rm -rf .nuxtrc`.

**Comment by LynxTR** [comment]
I am also seeing this one: 

`ERROR  Error while requiring module /home/lynx/.nvm/versions/node/v16.19.0/lib/node_modules/@nuxt/devtools: Error: EISDIR: illegal operation on a directory, read`

Seems like @nuxt/devtools are not allowed to access .nvm, .nuxtrc and so on?

**Comment by pvenableh** [comment]
> The easiest way to get back up and running is to go to your home directory (`cd ~`) and delete the `.nuxtrc` file with `rm -rf .nuxtrc`. @rahulkumarsingh73690 @toniengelhardt.

Had this error for the past few days and removing .nuxtrc from my home directory fixed it.  Thanks!

**Comment by Extarys** [comment]
Under Fedora here, same issue enabled or disabled.
:fire: Cursed command! :P

**Comment by jpcarpenter** [comment]
Encountering this same issue. Anybody know where the `.nuxtrc` file would be located if not within the home directory? Been trying to search for it for hours now.

**Comment by antfu** [comment]
It should be fixed by c572ed0ca3971ed05721a9f1505043efdd62e95d.

Running `npx nuxi@latest devtools enable` again should fix the issue (make sure `@nuxt/devtools@0.1.4` is invoked.

Sorry for the inconvenience.

**Comment by rahulkumarsingh73690** [comment]
Thanks @antfu, for quickly fixing this issue.
