### ISSUE TITLE
typeerror, cannot make it work

### ISSUE THREAD

**Issue by masterkain** [nuxt/devtools#80]
I'm using nuxt in development in a docker compose setup, reverse proxied by a web server with ssl termination and in a docker container.

I get an error after connecting to ws and that's it.

<img width="793" alt="Screen Shot 2023-02-18 at 22 18 24" src="https://user-images.githubusercontent.com/12844/219900008-f3d8d257-f971-4edd-a19e-f8a0580183f0.png">

**Comment by antfu** [comment]
Does it work for you without a docker env?

**Comment by antfu** [comment]
Close due to inactive
