### ISSUE TITLE
failed to load url `/@fs/C:...../@nuxt/devtools/node_modules/vite-plugin-vue-inspector/src/load.js`

### ISSUE THREAD

**Issue by huang-julien** [nuxt/devtools#81]
Hi ! :wave: on windows i've got an issue to load the devtools. If i remember well, there was an issue similar to this one a few months ago on nuxt 3 RC.

Log: 
````
 Failed to load url /@fs/C:/.../AppData/Roaming/nvm/v16.19.0/node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector/src/load.js (resolved id: C:/Users/chakr/AppData/Roaming/nvm/v16.19.0/node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector/src/load.js?v=d01c9f94). Does the file exist?`

 Failed to load url /@fs/C:/.../AppData/Roaming/nvm/v16.19.0/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs?v=d01c9f94 (resolved id: C:/Users/chakr/AppData/Roaming/nvm/v16.19.0/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs?v=d01c9f94). Does the file exist?

 ````

**Comment by huang-julien** [comment]
Additionnal logs: 
ERROR  The request url "C:/Users/.../AppData/Roaming/nvm/v16.19.0/node_modules/@nuxt/devtools/node_modules/vite-plugin-vue-inspector/src/load.js" is outside of Vite serving allow list.

**Comment by tlebeitsuk** [comment]
I had the same problem when I upgraded Node. Fixed it by changing version in .nuxtrc (located in the home folder).

**Comment by huang-julien** [comment]
I'll try this tonight :+1: , btw this only triggers with `nuxi devtools enable` and i can't disable it anymore :joy: (for now) . The only workaround is to set the module within the nuxt project deps and to enable it through the config file

**Comment by tlebeitsuk** [comment]
Updating .nuxtrc will also fix that.

**Comment by huang-julien** [comment]
It works thank you @tlebeitsuk !
I think this can be considered as a bug. I'll leave this open

**Comment by alvarosabu** [comment]
Same here, also it's not possible to disable it by using `nuxi devtools disable` #84

**Comment by antfu** [comment]
If should be fixed if you run `nuxi devtools enable` again, or try with `nuxi devtools disable --remove`
