### ISSUE TITLE
Does not disable

### ISSUE THREAD

**Issue by milieugrotesque** [nuxt/devtools#83]
Hi guys,

so i just tested these devtools, but now I cannot disable it anymore.
Even though it says

`Nuxt Devtools is not enabled for this project. `

I always get

`✔ Nuxt Devtools is enabled v0.1.2 (experimental)   `

Also if i switch to another project which runs on Node 16, I always get Node 18 errors as this was the version i initially installed the devtools.

`The request url "/Users/…/.nvm/versions/node/v18.10.0/lib/node_modules/@nuxt/devtools/dist/runtime/plugins/devtools.client.mjs" is outside of Vite serving allow list.`

Therefor I cannot use any of my other nuxt3 projects anymore.

How to fix this?

**Comment by antfu** [comment]
Can you provide the content of your `~/.nuxtrc`? Or try removing it and running the command again.

**Comment by milieugrotesque** [comment]
I accidently was logged into this wrong account. Please delete this issue @antfu, I will reopen another issue.
