### ISSUE TITLE
bug: nvm switch node version

### ISSUE THREAD

**Issue by cpreston321** [nuxt/devtools#86]
OS: **Mac OS**
Package Manager: **PNPM**
Nuxt Version: **3.2.2**
Nuxi Verison: **3.2.2**

When switching node versions using `nvm`. 

In my case I enabled `npx nuxi devtools enable` on node 18.7.0 and started the project project. It added the project to the `.nuxtrc` file which was fine. It was appending the version devtools path appending path to `18.7.0` global node folder. I switch node versions on a different project to `18.9.0` and ran `npx nuxi devtools enable` on my second project. I then ran `npx nuxi dev` it then started up and I got a bunch of errors to dependancies that where within the devtools global folder.

I looked at the global `.nuxtrc` file and it never appended my project path and didn't change the devtools resolution path it was still pointing to `.../18.7.0/node_modules/@nuxt/devtools`. So I deleted the file and re-enabled it and it started working as intended. 

I think this is a edge case but I just want to let you know! If you need any information please let me know. I can't really re-produce on stackblitz since it has to be locally with `nvm`. 

Thanks,
CP

**Comment by Atinux** [comment]
I do have some errors too using Volta.sh as node versioning manager.

In that case I recommend you to remove the devtools from `~/.nuxtrc` and install it locally with `npm -i D @nuxt/devtools` and adding it in your `nuxt.config.ts`

**Comment by cpreston321** [comment]
@Atinux Okay, sounds good!

You think it would be useful to add it to the install docs as note for now?

Thanks,
CP

**Comment by Atinux** [comment]
I think so too, WDYT @antfu ?

**Comment by cpreston321** [comment]
@antfu you are a absolute beast 💯 

Thanks 💚
