### ISSUE TITLE
Asset viewer enhancement

### ISSUE THREAD

**Issue by Atinux** [nuxt/devtools#91]
Someone made a Nuxt module when the devtools did not exist to view the images in the public directory: https://github.com/cssninjaStudio/nuxt-media-viewer

Here's a preview in the nuxt.com website:
http://volta.s3.fr-par.scw.cloud/Clean_Shot_2023_02_23_at_14_12_17_30d1684814.mp4

The downside is that it extends the Nuxt pages so the implementation in not correct but I do love the idea.

Maybe something we could add with Nuxt Image module?

**Comment by antfu** [comment]
Do you think we should reuse it (and maybe improve upstream?) or should we implement on ourselves?

**Comment by Atinux** [comment]
I think we shall implement it ourselves but take inspiration from it

**Comment by antfu** [comment]
The first implementation is in #120 

A few TODOs:

- [ ] Able to edit plain text content directly
- [ ] Drag & Drop to upload
- [ ] Tree view for list mode
- [ ] Integration with `@nuxt/image` module (optimize images by one click, etc.)

**Comment by arashsheyda** [comment]
> The first implementation is in #120
> 
> A few TODOs:
> 
> * [ ]  Able to edit plain text content directly
> * [ ]  Drag & Drop to upload
> * [ ]  Tree view for list mode
> * [ ]  Integration with `@nuxt/image` module (optimize images by one click, etc.)

is something [this](https://res.cloudinary.com/arashsheyda/video/upload/v1680256281/nuxt/dropzone-20230331_124332_l5ezyt.mp4) good for Drag & Drop to upload? for start? [video](https://res.cloudinary.com/arashsheyda/video/upload/v1680256281/nuxt/dropzone-20230331_124332_l5ezyt.mp4)

**Comment by antfu** [comment]
@arashsheyda You could send a PR and we could discuss it. For me I could like to directly make the panel drop-able, so saving one extra action to open the panel.
